# Generated by scripts/helion_aot.py; do not edit.
# ruff: noqa
# fmt: off
"""
Auto-generated heuristics for kernels: _dtw_dp_kernel, _dag_forward_kernel
Backend: decision_tree

Provides for each kernel:
- key_<kernel>(*args): Cache key function
- autotune_<kernel>(*args): Config selection function
"""

import torch

# === Kernel: _dtw_dp_kernel ===


def key__dtw_dp_kernel(*args) -> int:
    """Select config index for the given arguments (also serves as cache key)."""
    _arg0_dim2 = int(args[0].shape[2]) if len(args) > 0 and isinstance(args[0], torch.Tensor) and args[0].ndim > 2 else 0
    _arg1_scalar = args[1] if len(args) > 1 and isinstance(args[1], (int, float)) else 0
    _arg2_scalar = args[2] if len(args) > 2 and isinstance(args[2], (int, float)) else 0
    if _arg0_dim2 <= 1024.0:
        if _arg1_scalar <= 0.0:
            if _arg0_dim2 <= 128.0:
                return 0
            else:
                if _arg2_scalar <= 0.0:
                    if _arg0_dim2 <= 256.0:
                        return 3
                    else:
                        return 0
                else:
                    return 3
        else:
            if _arg0_dim2 <= 512.0:
                if _arg0_dim2 <= 128.0:
                    return 1
                else:
                    return 1
            else:
                return 1
    else:
        if _arg0_dim2 <= 4096.0:
            if _arg0_dim2 <= 2048.0:
                return 0
            else:
                if _arg1_scalar <= 0.0:
                    return 0
                else:
                    if _arg2_scalar <= 0.0:
                        return 0
                    else:
                        return 2
        else:
            if _arg1_scalar <= 0.0:
                return 1
            else:
                return 2


def autotune__dtw_dp_kernel(*args) -> dict:
    """Select the optimal config for the given arguments."""
    _C = [
        {'block_sizes': [], 'range_unroll_factors': [0, 3], 'range_warp_specializes': [None, None], 'range_num_stages': [0, 3], 'range_multi_buffers': [False, None], 'range_flattens': [None, True], 'load_eviction_policies': ['', '', ''], 'num_warps': 16, 'num_stages': 1, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'persistent_interleaved', 'num_sm_multiplier': 8},
        {'block_sizes': [], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [None, None], 'range_num_stages': [0, 3], 'range_multi_buffers': [None, False], 'range_flattens': [None, None], 'load_eviction_policies': ['', 'last', ''], 'num_warps': 8, 'num_stages': 1, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [None, None], 'range_num_stages': [0, 0], 'range_multi_buffers': [None, None], 'range_flattens': [None, False], 'load_eviction_policies': ['last', '', ''], 'num_warps': 16, 'num_stages': 1, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'persistent_blocked', 'num_sm_multiplier': 1},
        {'block_sizes': [], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [None, None], 'range_num_stages': [0, 0], 'range_multi_buffers': [None, None], 'range_flattens': [None, None], 'load_eviction_policies': ['last', 'last', '', ''], 'num_warps': 8, 'num_stages': 5, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
    ]
    return _C[key__dtw_dp_kernel(*args)]


# === Kernel: _dag_forward_kernel ===


def key__dag_forward_kernel(*args) -> int:
    """Select config index for the given arguments (also serves as cache key)."""
    _arg0_dim2 = int(args[0].shape[2]) if len(args) > 0 and isinstance(args[0], torch.Tensor) and args[0].ndim > 2 else 0
    if _arg0_dim2 <= 512.0:
        return 0
    else:
        if _arg0_dim2 <= 2048.0:
            return 2
        else:
            return 1


def autotune__dag_forward_kernel(*args) -> dict:
    """Select the optimal config for the given arguments."""
    _C = [
        {'block_sizes': [], 'range_unroll_factors': [0, 4], 'range_warp_specializes': [None, None], 'range_num_stages': [0, 3], 'range_multi_buffers': [None, None], 'range_flattens': [None, None], 'load_eviction_policies': ['', '', '', '', '', '', '', 'first', '', '', ''], 'num_warps': 1, 'num_stages': 2, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [None, None], 'range_num_stages': [0, 0], 'range_multi_buffers': [None, None], 'range_flattens': [None, True], 'load_eviction_policies': ['', '', '', '', '', '', '', '', '', '', ''], 'num_warps': 32, 'num_stages': 1, 'indexing': ['pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
        {'block_sizes': [], 'range_unroll_factors': [0, 0], 'range_warp_specializes': [None, None], 'range_num_stages': [0, 0], 'range_multi_buffers': [None, True], 'range_flattens': [None, True], 'load_eviction_policies': ['', '', '', '', '', 'last', '', '', '', '', ''], 'num_warps': 16, 'num_stages': 3, 'indexing': ['pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer', 'pointer', 'pointer', 'pointer', 'tensor_descriptor', 'pointer'], 'atomic_indexing': [], 'pid_type': 'flat'},
    ]
    return _C[key__dag_forward_kernel(*args)]
