# Generated by scripts/helion_aot.py; do not edit.
# ruff: noqa
# fmt: off
# Auto-generated standalone Triton kernel for '_contract_over_i'.
# No Helion dependency required at runtime.

from __future__ import annotations

import torch
import triton
import triton.language as tl


def _default_launcher(
    triton_kernel,
    grid,
    *args,
    num_warps,
    num_stages,
    launch_cooperative_grid=False,
    **kwargs,
):
    return triton_kernel.run(
        *args,
        grid=grid,
        warmup=False,
        num_warps=num_warps,
        num_stages=num_stages,
        launch_cooperative_grid=launch_cooperative_grid,
        **kwargs,
    )


# =================================================================
# Config 0
# =================================================================

_BLOCK_SIZE_1_c0 = tl.constexpr(16)
_BLOCK_SIZE_2_c0 = tl.constexpr(16)
_BLOCK_SIZE_0_c0 = tl.constexpr(1)
_BLOCK_SIZE_3_c0 = tl.constexpr(16)

@triton.jit
def _helion__contract_over_i_c0(c, a, b, x, y, z, out, a_stride_0, a_stride_1, a_stride_2, b_stride_0, b_stride_1, b_stride_2, c_stride_0, c_stride_1, c_stride_2, out_stride_0, out_stride_1, out_stride_2, x_stride_0, x_stride_1, x_stride_2, y_stride_0, y_stride_1, y_stride_2, z_stride_0, z_stride_1, z_stride_2, n_j, n_k, n_p, n_i):
    # src[_semiring_helion.py:145]: for tile_p, tile_j, tile_k in hl.tile([n_p, n_j, n_k]):
    num_blocks_0 = n_p
    num_blocks_1 = tl.cdiv(n_j, _BLOCK_SIZE_1_c0)
    pid_0 = tl.program_id(0) % num_blocks_0
    pid_1 = tl.program_id(0) // num_blocks_0 % num_blocks_1
    pid_2 = tl.program_id(0) // (num_blocks_0 * num_blocks_1)
    offset_0 = pid_0
    indices_0 = offset_0 + tl.zeros([1], tl.int32)
    offset_1 = pid_1 * _BLOCK_SIZE_1_c0
    indices_1 = (offset_1 + tl.arange(0, _BLOCK_SIZE_1_c0)).to(tl.int32)
    mask_1 = indices_1 < n_j
    offset_2 = pid_2 * _BLOCK_SIZE_2_c0
    indices_2 = (offset_2 + tl.arange(0, _BLOCK_SIZE_2_c0)).to(tl.int32)
    mask_2 = indices_2 < n_k
    # src[_semiring_helion.py:146]: acc = hl.zeros([tile_p, tile_j, tile_k], dtype=b.dtype)
    acc = tl.full([_BLOCK_SIZE_0_c0, _BLOCK_SIZE_1_c0, _BLOCK_SIZE_2_c0], 0.0, tl.float64)
    # src[_semiring_helion.py:147]: for tile_i in hl.tile(n_i):
    # src[_semiring_helion.py:148]:     cc = c[tile_p, tile_i, tile_k][:, :, None, :]
    # src[_semiring_helion.py:149]:     terms = (
    # src[_semiring_helion.py:147-161]: ...
    for offset_3 in tl.range(0, tl.cast(n_i, tl.int32), _BLOCK_SIZE_3_c0):
        indices_3 = offset_3 + tl.arange(0, _BLOCK_SIZE_3_c0).to(tl.int32)
        mask_3 = indices_3 < n_i
        acc_copy = acc
        acc_copy_0 = acc_copy
        # src[_semiring_helion.py:148]: cc = c[tile_p, tile_i, tile_k][:, :, None, :]
        load = tl.load(c + (indices_0[:, None, None] * c_stride_0 + indices_3[None, :, None] * c_stride_1 + indices_2[None, None, :] * c_stride_2), mask_3[None, :, None] & mask_2[None, None, :], other=0)
        cc = load[:, :, None, :]
        # src[_semiring_helion.py:150]: a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
        load_1 = tl.load(a + (indices_0[:, None, None] * a_stride_0 + indices_3[None, :, None] * a_stride_1 + indices_1[None, None, :] * a_stride_2), mask_3[None, :, None] & mask_1[None, None, :], other=0)
        subscript_1 = load_1[:, :, :, None]
        load_2 = tl.load(b + (indices_0[:, None, None] * b_stride_0 + indices_1[None, :, None] * b_stride_1 + indices_2[None, None, :] * b_stride_2), mask_1[None, :, None] & mask_2[None, None, :], other=0)
        subscript_2 = load_2[:, None, :, :]
        v_0 = subscript_1 + subscript_2
        # src[_semiring_helion.py:153]: w = torch.where((terms == cc) & (cc != float("-inf")), 1.0, 0.0)
        v_1 = v_0 == cc
        v_2 = tl.full([], float('-inf'), tl.float64)
        v_3 = cc != v_2
        v_4 = v_1 & v_3
        scalar_tensor = tl.full([], 0.0, tl.float32)
        scalar_tensor_1 = tl.full([], 1.0, tl.float32)
        where = tl.where(v_4, scalar_tensor_1, scalar_tensor)
        # src[_semiring_helion.py:158]: * x[tile_p, tile_i, tile_j][:, :, :, None]
        load_3 = tl.load(x + (indices_0[:, None, None] * x_stride_0 + indices_3[None, :, None] * x_stride_1 + indices_1[None, None, :] * x_stride_2), mask_3[None, :, None] & mask_1[None, None, :], other=0)
        subscript_3 = load_3[:, :, :, None]
        # src[_semiring_helion.py:157]: w
        # src[_semiring_helion.py:158]: * x[tile_p, tile_i, tile_j][:, :, :, None]
        v_5 = tl.cast(where, tl.float64)
        v_6 = v_5 * subscript_3
        # src[_semiring_helion.py:159]: * y[tile_p, tile_i, tile_k][:, :, None, :],
        load_4 = tl.load(y + (indices_0[:, None, None] * y_stride_0 + indices_3[None, :, None] * y_stride_1 + indices_2[None, None, :] * y_stride_2), mask_3[None, :, None] & mask_2[None, None, :], other=0)
        subscript_4 = load_4[:, :, None, :]
        # src[_semiring_helion.py:157]: w
        # src[_semiring_helion.py:158]: * x[tile_p, tile_i, tile_j][:, :, :, None]
        # src[_semiring_helion.py:159]: * y[tile_p, tile_i, tile_k][:, :, None, :],
        v_7 = v_6 * subscript_4
        # src[_semiring_helion.py:156]: acc = acc + torch.sum(
        # src[_semiring_helion.py:157]:     w
        # src[_semiring_helion.py:158]:     * x[tile_p, tile_i, tile_j][:, :, :, None]
        # src[_semiring_helion.py:156-161]: ...
        sum_1 = tl.cast(tl.sum(v_7, 1), tl.float64)
        acc = acc_copy_0 + sum_1
    # src[_semiring_helion.py:162]: out[tile_p, tile_j, tile_k] = acc * z[tile_p, tile_j, tile_k]
    load_5 = tl.load(z + (indices_0[:, None, None] * z_stride_0 + indices_1[None, :, None] * z_stride_1 + indices_2[None, None, :] * z_stride_2), mask_1[None, :, None] & mask_2[None, None, :], other=0)
    v_9 = acc * load_5
    tl.store(out + (indices_0[:, None, None] * out_stride_0 + indices_1[None, :, None] * out_stride_1 + indices_2[None, None, :] * out_stride_2), v_9, mask_1[None, :, None] & mask_2[None, None, :])

def __contract_over_i_c0(a: Tensor, b: Tensor, c: Tensor, x: Tensor, y: Tensor, z: Tensor, is_max: hl.constexpr, *, _launcher=_default_launcher):
    """R[p, j, k] = z[p, j, k] sum_i W x[p, i, j] y[p, i, k]."""
    # src[_semiring_helion.py:142]: n_p, n_i, n_j = a.shape
    n_p, n_i, n_j = a.shape
    # src[_semiring_helion.py:143]: n_k = b.size(-1)
    n_k = b.size(-1)
    # src[_semiring_helion.py:144]: out = torch.empty_like(b)
    out = torch.empty_like(b)
    # src[_semiring_helion.py:145]: for tile_p, tile_j, tile_k in hl.tile([n_p, n_j, n_k]):
    _BLOCK_SIZE_1_c0 = 16
    _BLOCK_SIZE_2_c0 = 16
    # src[_semiring_helion.py:145]: for tile_p, tile_j, tile_k in hl.tile([n_p, n_j, n_k]):
    # src[_semiring_helion.py:146]:     acc = hl.zeros([tile_p, tile_j, tile_k], dtype=b.dtype)
    # src[_semiring_helion.py:147]:     for tile_i in hl.tile(n_i):
    # src[_semiring_helion.py:145-162]: ...
    _launcher(_helion__contract_over_i_c0, (n_p * ((n_j + _BLOCK_SIZE_1_c0 - 1) // _BLOCK_SIZE_1_c0) * ((n_k + _BLOCK_SIZE_2_c0 - 1) // _BLOCK_SIZE_2_c0),), c, a, b, x, y, z, out, a.stride(0), a.stride(1), a.stride(2), b.stride(0), b.stride(1), b.stride(2), c.stride(0), c.stride(1), c.stride(2), out.stride(0), out.stride(1), out.stride(2), x.stride(0), x.stride(1), x.stride(2), y.stride(0), y.stride(1), y.stride(2), z.stride(0), z.stride(1), z.stride(2), n_j, n_k, n_p, n_i, num_warps=4, num_stages=1)
    # src[_semiring_helion.py:163]: return out
    return out

# =================================================================
# Config 1
# =================================================================

_BLOCK_SIZE_0_c1 = tl.constexpr(16)
_BLOCK_SIZE_1_c1 = tl.constexpr(2)
_BLOCK_SIZE_2_c1 = tl.constexpr(4)
_BLOCK_SIZE_3_c1 = tl.constexpr(4)

@triton.jit
def _helion__contract_over_i_c1(c, a, b, x, y, z, out, a_stride_0, a_stride_1, a_stride_2, b_stride_0, b_stride_1, b_stride_2, c_stride_0, c_stride_1, c_stride_2, out_stride_0, out_stride_1, out_stride_2, x_stride_0, x_stride_1, x_stride_2, y_stride_0, y_stride_1, y_stride_2, z_stride_0, z_stride_1, z_stride_2, n_p, n_j, n_k, n_i):
    # src[_semiring_helion.py:145]: for tile_p, tile_j, tile_k in hl.tile([n_p, n_j, n_k]):
    num_blocks_0 = tl.cdiv(n_p, _BLOCK_SIZE_0_c1)
    num_blocks_1 = tl.cdiv(n_j, _BLOCK_SIZE_1_c1)
    pid_0 = tl.program_id(0) % num_blocks_0
    pid_1 = tl.program_id(0) // num_blocks_0 % num_blocks_1
    pid_2 = tl.program_id(0) // (num_blocks_0 * num_blocks_1)
    offset_0 = pid_0 * _BLOCK_SIZE_0_c1
    indices_0 = (offset_0 + tl.arange(0, _BLOCK_SIZE_0_c1)).to(tl.int32)
    mask_0 = indices_0 < n_p
    offset_1 = pid_1 * _BLOCK_SIZE_1_c1
    indices_1 = (offset_1 + tl.arange(0, _BLOCK_SIZE_1_c1)).to(tl.int32)
    mask_1 = indices_1 < n_j
    offset_2 = pid_2 * _BLOCK_SIZE_2_c1
    indices_2 = (offset_2 + tl.arange(0, _BLOCK_SIZE_2_c1)).to(tl.int32)
    mask_2 = indices_2 < n_k
    # src[_semiring_helion.py:146]: acc = hl.zeros([tile_p, tile_j, tile_k], dtype=b.dtype)
    acc = tl.full([_BLOCK_SIZE_0_c1, _BLOCK_SIZE_1_c1, _BLOCK_SIZE_2_c1], 0.0, tl.float64)
    # src[_semiring_helion.py:147]: for tile_i in hl.tile(n_i):
    # src[_semiring_helion.py:148]:     cc = c[tile_p, tile_i, tile_k][:, :, None, :]
    # src[_semiring_helion.py:149]:     terms = (
    # src[_semiring_helion.py:147-161]: ...
    for offset_3 in tl.range(0, tl.cast(n_i, tl.int32), _BLOCK_SIZE_3_c1):
        indices_3 = offset_3 + tl.arange(0, _BLOCK_SIZE_3_c1).to(tl.int32)
        mask_3 = indices_3 < n_i
        acc_copy = acc
        acc_copy_0 = acc_copy
        # src[_semiring_helion.py:148]: cc = c[tile_p, tile_i, tile_k][:, :, None, :]
        load = tl.load(c + (indices_0[:, None, None] * c_stride_0 + indices_3[None, :, None] * c_stride_1 + indices_2[None, None, :] * c_stride_2), mask_0[:, None, None] & mask_3[None, :, None] & mask_2[None, None, :], other=0)
        cc = load[:, :, None, :]
        # src[_semiring_helion.py:150]: a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
        load_1 = tl.load(a + (indices_0[:, None, None] * a_stride_0 + indices_3[None, :, None] * a_stride_1 + indices_1[None, None, :] * a_stride_2), mask_0[:, None, None] & mask_3[None, :, None] & mask_1[None, None, :], other=0)
        subscript_1 = load_1[:, :, :, None]
        load_2 = tl.load(b + (indices_0[:, None, None] * b_stride_0 + indices_1[None, :, None] * b_stride_1 + indices_2[None, None, :] * b_stride_2), mask_0[:, None, None] & mask_1[None, :, None] & mask_2[None, None, :], other=0)
        subscript_2 = load_2[:, None, :, :]
        v_0 = subscript_1 + subscript_2
        # src[_semiring_helion.py:153]: w = torch.where((terms == cc) & (cc != float("-inf")), 1.0, 0.0)
        v_1 = v_0 == cc
        v_2 = tl.full([], float('-inf'), tl.float64)
        v_3 = cc != v_2
        v_4 = v_1 & v_3
        scalar_tensor = tl.full([], 0.0, tl.float32)
        scalar_tensor_1 = tl.full([], 1.0, tl.float32)
        where = tl.where(v_4, scalar_tensor_1, scalar_tensor)
        # src[_semiring_helion.py:158]: * x[tile_p, tile_i, tile_j][:, :, :, None]
        load_3 = tl.load(x + (indices_0[:, None, None] * x_stride_0 + indices_3[None, :, None] * x_stride_1 + indices_1[None, None, :] * x_stride_2), mask_0[:, None, None] & mask_3[None, :, None] & mask_1[None, None, :], other=0)
        subscript_3 = load_3[:, :, :, None]
        # src[_semiring_helion.py:157]: w
        # src[_semiring_helion.py:158]: * x[tile_p, tile_i, tile_j][:, :, :, None]
        v_5 = tl.cast(where, tl.float64)
        v_6 = v_5 * subscript_3
        # src[_semiring_helion.py:159]: * y[tile_p, tile_i, tile_k][:, :, None, :],
        load_4 = tl.load(y + (indices_0[:, None, None] * y_stride_0 + indices_3[None, :, None] * y_stride_1 + indices_2[None, None, :] * y_stride_2), mask_0[:, None, None] & mask_3[None, :, None] & mask_2[None, None, :], other=0)
        subscript_4 = load_4[:, :, None, :]
        # src[_semiring_helion.py:157]: w
        # src[_semiring_helion.py:158]: * x[tile_p, tile_i, tile_j][:, :, :, None]
        # src[_semiring_helion.py:159]: * y[tile_p, tile_i, tile_k][:, :, None, :],
        v_7 = v_6 * subscript_4
        # src[_semiring_helion.py:156]: acc = acc + torch.sum(
        # src[_semiring_helion.py:157]:     w
        # src[_semiring_helion.py:158]:     * x[tile_p, tile_i, tile_j][:, :, :, None]
        # src[_semiring_helion.py:156-161]: ...
        sum_1 = tl.cast(tl.sum(v_7, 1), tl.float64)
        acc = acc_copy_0 + sum_1
    # src[_semiring_helion.py:162]: out[tile_p, tile_j, tile_k] = acc * z[tile_p, tile_j, tile_k]
    load_5 = tl.load(z + (indices_0[:, None, None] * z_stride_0 + indices_1[None, :, None] * z_stride_1 + indices_2[None, None, :] * z_stride_2), mask_0[:, None, None] & mask_1[None, :, None] & mask_2[None, None, :], other=0)
    v_9 = acc * load_5
    tl.store(out + (indices_0[:, None, None] * out_stride_0 + indices_1[None, :, None] * out_stride_1 + indices_2[None, None, :] * out_stride_2), v_9, mask_0[:, None, None] & mask_1[None, :, None] & mask_2[None, None, :])

def __contract_over_i_c1(a: Tensor, b: Tensor, c: Tensor, x: Tensor, y: Tensor, z: Tensor, is_max: hl.constexpr, *, _launcher=_default_launcher):
    """R[p, j, k] = z[p, j, k] sum_i W x[p, i, j] y[p, i, k]."""
    # src[_semiring_helion.py:142]: n_p, n_i, n_j = a.shape
    n_p, n_i, n_j = a.shape
    # src[_semiring_helion.py:143]: n_k = b.size(-1)
    n_k = b.size(-1)
    # src[_semiring_helion.py:144]: out = torch.empty_like(b)
    out = torch.empty_like(b)
    # src[_semiring_helion.py:145]: for tile_p, tile_j, tile_k in hl.tile([n_p, n_j, n_k]):
    _BLOCK_SIZE_0_c1 = 16
    _BLOCK_SIZE_1_c1 = 2
    _BLOCK_SIZE_2_c1 = 4
    # src[_semiring_helion.py:145]: for tile_p, tile_j, tile_k in hl.tile([n_p, n_j, n_k]):
    # src[_semiring_helion.py:146]:     acc = hl.zeros([tile_p, tile_j, tile_k], dtype=b.dtype)
    # src[_semiring_helion.py:147]:     for tile_i in hl.tile(n_i):
    # src[_semiring_helion.py:145-162]: ...
    _launcher(_helion__contract_over_i_c1, ((n_p + _BLOCK_SIZE_0_c1 - 1) // _BLOCK_SIZE_0_c1 * ((n_j + _BLOCK_SIZE_1_c1 - 1) // _BLOCK_SIZE_1_c1) * ((n_k + _BLOCK_SIZE_2_c1 - 1) // _BLOCK_SIZE_2_c1),), c, a, b, x, y, z, out, a.stride(0), a.stride(1), a.stride(2), b.stride(0), b.stride(1), b.stride(2), c.stride(0), c.stride(1), c.stride(2), out.stride(0), out.stride(1), out.stride(2), x.stride(0), x.stride(1), x.stride(2), y.stride(0), y.stride(1), y.stride(2), z.stride(0), z.stride(1), z.stride(2), n_p, n_j, n_k, n_i, num_warps=2, num_stages=1)
    # src[_semiring_helion.py:163]: return out
    return out

# =================================================================
# Config 2
# =================================================================

_BLOCK_SIZE_1_c2 = tl.constexpr(16)
_BLOCK_SIZE_2_c2 = tl.constexpr(16)
_BLOCK_SIZE_0_c2 = tl.constexpr(1)
_BLOCK_SIZE_3_c2 = tl.constexpr(16)

@triton.jit
def _helion__contract_over_i_c2(c, a, b, x, y, z, out, a_stride_0, a_stride_1, a_stride_2, b_stride_0, b_stride_1, b_stride_2, c_stride_0, c_stride_1, c_stride_2, out_stride_0, out_stride_1, out_stride_2, x_stride_0, x_stride_1, x_stride_2, y_stride_0, y_stride_1, y_stride_2, z_stride_0, z_stride_1, z_stride_2, n_j, n_k, n_p, n_i):
    # src[_semiring_helion.py:145]: for tile_p, tile_j, tile_k in hl.tile([n_p, n_j, n_k]):
    num_blocks_0 = n_p
    num_blocks_1 = tl.cdiv(n_j, _BLOCK_SIZE_1_c2)
    pid_0 = tl.program_id(0) % num_blocks_0
    pid_1 = tl.program_id(0) // num_blocks_0 % num_blocks_1
    pid_2 = tl.program_id(0) // (num_blocks_0 * num_blocks_1)
    offset_0 = pid_0
    indices_0 = offset_0 + tl.zeros([1], tl.int32)
    offset_1 = pid_1 * _BLOCK_SIZE_1_c2
    indices_1 = (offset_1 + tl.arange(0, _BLOCK_SIZE_1_c2)).to(tl.int32)
    mask_1 = indices_1 < n_j
    offset_2 = pid_2 * _BLOCK_SIZE_2_c2
    indices_2 = (offset_2 + tl.arange(0, _BLOCK_SIZE_2_c2)).to(tl.int32)
    mask_2 = indices_2 < n_k
    # src[_semiring_helion.py:146]: acc = hl.zeros([tile_p, tile_j, tile_k], dtype=b.dtype)
    acc = tl.full([_BLOCK_SIZE_0_c2, _BLOCK_SIZE_1_c2, _BLOCK_SIZE_2_c2], 0.0, tl.float64)
    # src[_semiring_helion.py:147]: for tile_i in hl.tile(n_i):
    # src[_semiring_helion.py:148]:     cc = c[tile_p, tile_i, tile_k][:, :, None, :]
    # src[_semiring_helion.py:149]:     terms = (
    # src[_semiring_helion.py:147-161]: ...
    for offset_3 in tl.range(0, tl.cast(n_i, tl.int32), _BLOCK_SIZE_3_c2, num_stages=1, flatten=False):
        indices_3 = offset_3 + tl.arange(0, _BLOCK_SIZE_3_c2).to(tl.int32)
        mask_3 = indices_3 < n_i
        acc_copy = acc
        acc_copy_0 = acc_copy
        # src[_semiring_helion.py:148]: cc = c[tile_p, tile_i, tile_k][:, :, None, :]
        load = tl.load(c + (indices_0[:, None, None] * c_stride_0 + indices_3[None, :, None] * c_stride_1 + indices_2[None, None, :] * c_stride_2), mask_3[None, :, None] & mask_2[None, None, :], other=0)
        cc = load[:, :, None, :]
        # src[_semiring_helion.py:150]: a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
        load_1 = tl.load(a + (indices_0[:, None, None] * a_stride_0 + indices_3[None, :, None] * a_stride_1 + indices_1[None, None, :] * a_stride_2), mask_3[None, :, None] & mask_1[None, None, :], other=0)
        subscript_1 = load_1[:, :, :, None]
        load_2 = tl.load(b + (indices_0[:, None, None] * b_stride_0 + indices_1[None, :, None] * b_stride_1 + indices_2[None, None, :] * b_stride_2), mask_1[None, :, None] & mask_2[None, None, :], other=0)
        subscript_2 = load_2[:, None, :, :]
        v_0 = subscript_1 + subscript_2
        # src[_semiring_helion.py:153]: w = torch.where((terms == cc) & (cc != float("-inf")), 1.0, 0.0)
        v_1 = v_0 == cc
        v_2 = tl.full([], float('-inf'), tl.float64)
        v_3 = cc != v_2
        v_4 = v_1 & v_3
        scalar_tensor = tl.full([], 0.0, tl.float32)
        scalar_tensor_1 = tl.full([], 1.0, tl.float32)
        where = tl.where(v_4, scalar_tensor_1, scalar_tensor)
        # src[_semiring_helion.py:158]: * x[tile_p, tile_i, tile_j][:, :, :, None]
        load_3 = tl.load(x + (indices_0[:, None, None] * x_stride_0 + indices_3[None, :, None] * x_stride_1 + indices_1[None, None, :] * x_stride_2), mask_3[None, :, None] & mask_1[None, None, :], other=0)
        subscript_3 = load_3[:, :, :, None]
        # src[_semiring_helion.py:157]: w
        # src[_semiring_helion.py:158]: * x[tile_p, tile_i, tile_j][:, :, :, None]
        v_5 = tl.cast(where, tl.float64)
        v_6 = v_5 * subscript_3
        # src[_semiring_helion.py:159]: * y[tile_p, tile_i, tile_k][:, :, None, :],
        load_4 = tl.load(y + (indices_0[:, None, None] * y_stride_0 + indices_3[None, :, None] * y_stride_1 + indices_2[None, None, :] * y_stride_2), mask_3[None, :, None] & mask_2[None, None, :], other=0)
        subscript_4 = load_4[:, :, None, :]
        # src[_semiring_helion.py:157]: w
        # src[_semiring_helion.py:158]: * x[tile_p, tile_i, tile_j][:, :, :, None]
        # src[_semiring_helion.py:159]: * y[tile_p, tile_i, tile_k][:, :, None, :],
        v_7 = v_6 * subscript_4
        # src[_semiring_helion.py:156]: acc = acc + torch.sum(
        # src[_semiring_helion.py:157]:     w
        # src[_semiring_helion.py:158]:     * x[tile_p, tile_i, tile_j][:, :, :, None]
        # src[_semiring_helion.py:156-161]: ...
        sum_1 = tl.cast(tl.sum(v_7, 1), tl.float64)
        acc = acc_copy_0 + sum_1
    # src[_semiring_helion.py:162]: out[tile_p, tile_j, tile_k] = acc * z[tile_p, tile_j, tile_k]
    load_5 = tl.load(z + (indices_0[:, None, None] * z_stride_0 + indices_1[None, :, None] * z_stride_1 + indices_2[None, None, :] * z_stride_2), mask_1[None, :, None] & mask_2[None, None, :], other=0)
    v_9 = acc * load_5
    tl.store(out + (indices_0[:, None, None] * out_stride_0 + indices_1[None, :, None] * out_stride_1 + indices_2[None, None, :] * out_stride_2), v_9, mask_1[None, :, None] & mask_2[None, None, :])

def __contract_over_i_c2(a: Tensor, b: Tensor, c: Tensor, x: Tensor, y: Tensor, z: Tensor, is_max: hl.constexpr, *, _launcher=_default_launcher):
    """R[p, j, k] = z[p, j, k] sum_i W x[p, i, j] y[p, i, k]."""
    # src[_semiring_helion.py:142]: n_p, n_i, n_j = a.shape
    n_p, n_i, n_j = a.shape
    # src[_semiring_helion.py:143]: n_k = b.size(-1)
    n_k = b.size(-1)
    # src[_semiring_helion.py:144]: out = torch.empty_like(b)
    out = torch.empty_like(b)
    # src[_semiring_helion.py:145]: for tile_p, tile_j, tile_k in hl.tile([n_p, n_j, n_k]):
    _BLOCK_SIZE_1_c2 = 16
    _BLOCK_SIZE_2_c2 = 16
    # src[_semiring_helion.py:145]: for tile_p, tile_j, tile_k in hl.tile([n_p, n_j, n_k]):
    # src[_semiring_helion.py:146]:     acc = hl.zeros([tile_p, tile_j, tile_k], dtype=b.dtype)
    # src[_semiring_helion.py:147]:     for tile_i in hl.tile(n_i):
    # src[_semiring_helion.py:145-162]: ...
    _launcher(_helion__contract_over_i_c2, (n_p * ((n_j + _BLOCK_SIZE_1_c2 - 1) // _BLOCK_SIZE_1_c2) * ((n_k + _BLOCK_SIZE_2_c2 - 1) // _BLOCK_SIZE_2_c2),), c, a, b, x, y, z, out, a.stride(0), a.stride(1), a.stride(2), b.stride(0), b.stride(1), b.stride(2), c.stride(0), c.stride(1), c.stride(2), out.stride(0), out.stride(1), out.stride(2), x.stride(0), x.stride(1), x.stride(2), y.stride(0), y.stride(1), y.stride(2), z.stride(0), z.stride(1), z.stride(2), n_j, n_k, n_p, n_i, num_warps=1, num_stages=3)
    # src[_semiring_helion.py:163]: return out
    return out

# =================================================================
# Heuristic dispatch
# =================================================================

# === Kernel: _max_bmm_kernel ===


# === Kernel: _contract_over_i ===


def key__contract_over_i(*args) -> int:
    _arg0_dim1 = int(args[0].shape[1]) if len(args) > 0 and isinstance(args[0], torch.Tensor) and args[0].ndim > 1 else 0
    _arg6_scalar = args[6] if len(args) > 6 and isinstance(args[6], (int, float)) else 0
    if _arg0_dim1 <= 8.0:
        return 1
    else:
        if _arg0_dim1 <= 32.0:
            return 0
        else:
            if _arg6_scalar <= 0.0:
                return 0
            else:
                return 2


# === Kernel: _contract_over_j ===


# === Kernel: _contract_over_k ===



def _contract_over_i(*args, **kwargs):
    return [
        __contract_over_i_c0,
        __contract_over_i_c1,
        __contract_over_i_c2,
    ][key__contract_over_i(*args)](*args, **kwargs)
