# Generated by scripts/helion_aot.py; do not edit.
# ruff: noqa
# fmt: off
# Auto-generated standalone Triton kernel for '_contract_over_k'.
# No Helion dependency required at runtime.

from __future__ import annotations

from torch._inductor.runtime.triton_compat import libdevice
import torch
import triton
import triton.language as tl


def _default_launcher(
    triton_kernel,
    grid,
    *args,
    num_warps,
    num_stages,
    launch_cooperative_grid=False,
    **kwargs,
):
    return triton_kernel.run(
        *args,
        grid=grid,
        warmup=False,
        num_warps=num_warps,
        num_stages=num_stages,
        launch_cooperative_grid=launch_cooperative_grid,
        **kwargs,
    )


# =================================================================
# Config 0
# =================================================================

_BLOCK_SIZE_1_c0 = tl.constexpr(2)
_BLOCK_SIZE_0_c0 = tl.constexpr(16)
_BLOCK_SIZE_2_c0 = tl.constexpr(4)

@triton.jit
def _helion__contract_over_k_c0(c, a, b, y, z, x, out, a_stride_0, a_stride_1, a_stride_2, b_stride_0, b_stride_1, b_stride_2, c_stride_0, c_stride_1, c_stride_2, out_stride_0, out_stride_1, out_stride_2, x_stride_0, x_stride_1, x_stride_2, y_stride_0, y_stride_1, y_stride_2, z_stride_0, z_stride_1, z_stride_2, n_i, n_p, n_j, n_k):
    # src[_semiring_helion.py:116]: for tile_p, tile_i, tile_j in hl.tile([n_p, n_i, n_j]):
    num_blocks_0 = tl.cdiv(n_i, _BLOCK_SIZE_1_c0)
    num_blocks_1 = tl.cdiv(n_p, _BLOCK_SIZE_0_c0)
    pid_0 = tl.program_id(0) % num_blocks_0
    pid_1 = tl.program_id(0) // num_blocks_0 % num_blocks_1
    pid_2 = tl.program_id(0) // (num_blocks_0 * num_blocks_1)
    offset_1 = pid_0 * _BLOCK_SIZE_1_c0
    indices_1 = (offset_1 + tl.arange(0, _BLOCK_SIZE_1_c0)).to(tl.int32)
    mask_1 = indices_1 < n_i
    offset_0 = pid_1 * _BLOCK_SIZE_0_c0
    indices_0 = (offset_0 + tl.arange(0, _BLOCK_SIZE_0_c0)).to(tl.int32)
    mask_0 = indices_0 < n_p
    offset_2 = pid_2 * _BLOCK_SIZE_2_c0
    indices_2 = (offset_2 + tl.arange(0, _BLOCK_SIZE_2_c0)).to(tl.int32)
    mask_2 = indices_2 < n_j
    # src[_semiring_helion.py:117]: acc = hl.zeros([tile_p, tile_i, tile_j], dtype=a.dtype)
    acc = tl.full([_BLOCK_SIZE_0_c0, _BLOCK_SIZE_1_c0, _BLOCK_SIZE_2_c0], 0.0, tl.float32)
    # src[_semiring_helion.py:118]: for tile_k in hl.tile(n_k):
    # src[_semiring_helion.py:119]:     cc = c[tile_p, tile_i, tile_k][:, :, None, :]
    # src[_semiring_helion.py:120]:     terms = (
    # src[_semiring_helion.py:118-132]: ...
    for offset_3 in tl.range(0, tl.cast(n_k, tl.int32), flatten=False):
        indices_3 = offset_3 + tl.arange(0, 1).to(tl.int32)
        acc_copy = acc
        acc_copy_0 = acc_copy
        # src[_semiring_helion.py:119]: cc = c[tile_p, tile_i, tile_k][:, :, None, :]
        load = tl.load(c + (indices_0[:, None, None] * c_stride_0 + indices_1[None, :, None] * c_stride_1 + indices_3[None, None, :] * c_stride_2), mask_0[:, None, None] & mask_1[None, :, None], other=0)
        cc = load[:, :, None, :]
        # src[_semiring_helion.py:121]: a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
        load_1 = tl.load(a + (indices_0[:, None, None] * a_stride_0 + indices_1[None, :, None] * a_stride_1 + indices_2[None, None, :] * a_stride_2), mask_0[:, None, None] & mask_1[None, :, None] & mask_2[None, None, :], other=0)
        subscript_1 = load_1[:, :, :, None]
        load_2 = tl.load(b + (indices_0[:, None, None] * b_stride_0 + indices_2[None, :, None] * b_stride_1 + indices_3[None, None, :] * b_stride_2), mask_0[:, None, None] & mask_2[None, :, None], other=0)
        subscript_2 = load_2[:, None, :, :]
        v_0 = subscript_1 + subscript_2
        # src[_semiring_helion.py:126]: w = torch.where(cc == float("-inf"), 0.0, torch.exp(terms - cc))
        v_1 = tl.full([], float('-inf'), tl.float32)
        v_2 = cc == v_1
        v_3 = v_0 - cc
        v_4 = libdevice.exp(v_3)
        scalar_tensor = tl.full([], 0.0, tl.float32)
        where = tl.where(v_2, scalar_tensor, v_4)
        # src[_semiring_helion.py:129]: * y[tile_p, tile_i, tile_k][:, :, None, :]
        load_3 = tl.load(y + (indices_0[:, None, None] * y_stride_0 + indices_1[None, :, None] * y_stride_1 + indices_3[None, None, :] * y_stride_2), mask_0[:, None, None] & mask_1[None, :, None], other=0)
        subscript_3 = load_3[:, :, None, :]
        # src[_semiring_helion.py:128]: w
        # src[_semiring_helion.py:129]: * y[tile_p, tile_i, tile_k][:, :, None, :]
        v_5 = where * subscript_3
        # src[_semiring_helion.py:130]: * z[tile_p, tile_j, tile_k][:, None, :, :],
        load_4 = tl.load(z + (indices_0[:, None, None] * z_stride_0 + indices_2[None, :, None] * z_stride_1 + indices_3[None, None, :] * z_stride_2), mask_0[:, None, None] & mask_2[None, :, None], other=0)
        subscript_4 = load_4[:, None, :, :]
        # src[_semiring_helion.py:128]: w
        # src[_semiring_helion.py:129]: * y[tile_p, tile_i, tile_k][:, :, None, :]
        # src[_semiring_helion.py:130]: * z[tile_p, tile_j, tile_k][:, None, :, :],
        v_6 = v_5 * subscript_4
        # src[_semiring_helion.py:127]: acc = acc + torch.sum(
        # src[_semiring_helion.py:128]:     w
        # src[_semiring_helion.py:129]:     * y[tile_p, tile_i, tile_k][:, :, None, :]
        # src[_semiring_helion.py:127-132]: ...
        sum_1 = tl.cast(tl.sum(v_6, 3), tl.float32)
        acc = acc_copy_0 + sum_1
    # src[_semiring_helion.py:133]: out[tile_p, tile_i, tile_j] = acc * x[tile_p, tile_i, tile_j]
    load_5 = tl.load(x + (indices_0[:, None, None] * x_stride_0 + indices_1[None, :, None] * x_stride_1 + indices_2[None, None, :] * x_stride_2), mask_0[:, None, None] & mask_1[None, :, None] & mask_2[None, None, :], other=0)
    v_8 = acc * load_5
    tl.store(out + (indices_0[:, None, None] * out_stride_0 + indices_1[None, :, None] * out_stride_1 + indices_2[None, None, :] * out_stride_2), v_8, mask_0[:, None, None] & mask_1[None, :, None] & mask_2[None, None, :])

def __contract_over_k_c0(a: Tensor, b: Tensor, c: Tensor, x: Tensor, y: Tensor, z: Tensor, is_max: hl.constexpr, *, _launcher=_default_launcher):
    """R[p, i, j] = x[p, i, j] sum_k W y[p, i, k] z[p, j, k]."""
    # src[_semiring_helion.py:113]: n_p, n_i, n_j = a.shape
    n_p, n_i, n_j = a.shape
    # src[_semiring_helion.py:114]: n_k = b.size(-1)
    n_k = b.size(-1)
    # src[_semiring_helion.py:115]: out = torch.empty_like(a)
    out = torch.empty_like(a)
    # src[_semiring_helion.py:116]: for tile_p, tile_i, tile_j in hl.tile([n_p, n_i, n_j]):
    _BLOCK_SIZE_1_c0 = 2
    _BLOCK_SIZE_0_c0 = 16
    _BLOCK_SIZE_2_c0 = 4
    # src[_semiring_helion.py:116]: for tile_p, tile_i, tile_j in hl.tile([n_p, n_i, n_j]):
    # src[_semiring_helion.py:117]:     acc = hl.zeros([tile_p, tile_i, tile_j], dtype=a.dtype)
    # src[_semiring_helion.py:118]:     for tile_k in hl.tile(n_k):
    # src[_semiring_helion.py:116-133]: ...
    _launcher(_helion__contract_over_k_c0, ((n_i + _BLOCK_SIZE_1_c0 - 1) // _BLOCK_SIZE_1_c0 * ((n_p + _BLOCK_SIZE_0_c0 - 1) // _BLOCK_SIZE_0_c0) * ((n_j + _BLOCK_SIZE_2_c0 - 1) // _BLOCK_SIZE_2_c0),), c, a, b, y, z, x, out, a.stride(0), a.stride(1), a.stride(2), b.stride(0), b.stride(1), b.stride(2), c.stride(0), c.stride(1), c.stride(2), out.stride(0), out.stride(1), out.stride(2), x.stride(0), x.stride(1), x.stride(2), y.stride(0), y.stride(1), y.stride(2), z.stride(0), z.stride(1), z.stride(2), n_i, n_p, n_j, n_k, num_warps=4, num_stages=1)
    # src[_semiring_helion.py:134]: return out
    return out

# =================================================================
# Config 1
# =================================================================

_BLOCK_SIZE_1_c1 = tl.constexpr(16)
_BLOCK_SIZE_2_c1 = tl.constexpr(16)
_BLOCK_SIZE_0_c1 = tl.constexpr(1)
_BLOCK_SIZE_3_c1 = tl.constexpr(4)

@triton.jit
def _helion__contract_over_k_c1(c, a, b, y, z, x, out, a_stride_0, a_stride_1, a_stride_2, b_stride_0, b_stride_1, b_stride_2, c_stride_0, c_stride_1, c_stride_2, out_stride_0, out_stride_1, out_stride_2, x_stride_0, x_stride_1, x_stride_2, y_stride_0, y_stride_1, y_stride_2, z_stride_0, z_stride_1, z_stride_2, n_i, n_j, n_p, n_k):
    # src[_semiring_helion.py:116]: for tile_p, tile_i, tile_j in hl.tile([n_p, n_i, n_j]):
    num_blocks_0 = n_p
    num_blocks_1 = tl.cdiv(n_i, _BLOCK_SIZE_1_c1)
    pid_0 = tl.program_id(0) % num_blocks_0
    pid_1 = tl.program_id(0) // num_blocks_0 % num_blocks_1
    pid_2 = tl.program_id(0) // (num_blocks_0 * num_blocks_1)
    offset_0 = pid_0
    indices_0 = offset_0 + tl.zeros([1], tl.int32)
    offset_1 = pid_1 * _BLOCK_SIZE_1_c1
    indices_1 = (offset_1 + tl.arange(0, _BLOCK_SIZE_1_c1)).to(tl.int32)
    mask_1 = indices_1 < n_i
    offset_2 = pid_2 * _BLOCK_SIZE_2_c1
    indices_2 = (offset_2 + tl.arange(0, _BLOCK_SIZE_2_c1)).to(tl.int32)
    mask_2 = indices_2 < n_j
    # src[_semiring_helion.py:117]: acc = hl.zeros([tile_p, tile_i, tile_j], dtype=a.dtype)
    acc = tl.full([_BLOCK_SIZE_0_c1, _BLOCK_SIZE_1_c1, _BLOCK_SIZE_2_c1], 0.0, tl.float32)
    # src[_semiring_helion.py:118]: for tile_k in hl.tile(n_k):
    # src[_semiring_helion.py:119]:     cc = c[tile_p, tile_i, tile_k][:, :, None, :]
    # src[_semiring_helion.py:120]:     terms = (
    # src[_semiring_helion.py:118-132]: ...
    for offset_3 in tl.range(0, tl.cast(n_k, tl.int32), _BLOCK_SIZE_3_c1, disallow_acc_multi_buffer=False):
        indices_3 = offset_3 + tl.arange(0, _BLOCK_SIZE_3_c1).to(tl.int32)
        mask_3 = indices_3 < n_k
        acc_copy = acc
        acc_copy_0 = acc_copy
        # src[_semiring_helion.py:119]: cc = c[tile_p, tile_i, tile_k][:, :, None, :]
        load = tl.load(c + (indices_0[:, None, None] * c_stride_0 + indices_1[None, :, None] * c_stride_1 + indices_3[None, None, :] * c_stride_2), mask_1[None, :, None] & mask_3[None, None, :], other=0)
        cc = load[:, :, None, :]
        # src[_semiring_helion.py:121]: a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
        load_1 = tl.load(a + (indices_0[:, None, None] * a_stride_0 + indices_1[None, :, None] * a_stride_1 + indices_2[None, None, :] * a_stride_2), mask_1[None, :, None] & mask_2[None, None, :], other=0)
        subscript_1 = load_1[:, :, :, None]
        load_2 = tl.load(b + (indices_0[:, None, None] * b_stride_0 + indices_2[None, :, None] * b_stride_1 + indices_3[None, None, :] * b_stride_2), mask_2[None, :, None] & mask_3[None, None, :], other=0)
        subscript_2 = load_2[:, None, :, :]
        v_0 = subscript_1 + subscript_2
        # src[_semiring_helion.py:126]: w = torch.where(cc == float("-inf"), 0.0, torch.exp(terms - cc))
        v_1 = tl.full([], float('-inf'), tl.float32)
        v_2 = cc == v_1
        v_3 = v_0 - cc
        v_4 = libdevice.exp(v_3)
        scalar_tensor = tl.full([], 0.0, tl.float32)
        where = tl.where(v_2, scalar_tensor, v_4)
        # src[_semiring_helion.py:129]: * y[tile_p, tile_i, tile_k][:, :, None, :]
        load_3 = tl.load(y + (indices_0[:, None, None] * y_stride_0 + indices_1[None, :, None] * y_stride_1 + indices_3[None, None, :] * y_stride_2), mask_1[None, :, None] & mask_3[None, None, :], other=0)
        subscript_3 = load_3[:, :, None, :]
        # src[_semiring_helion.py:128]: w
        # src[_semiring_helion.py:129]: * y[tile_p, tile_i, tile_k][:, :, None, :]
        v_5 = where * subscript_3
        # src[_semiring_helion.py:130]: * z[tile_p, tile_j, tile_k][:, None, :, :],
        load_4 = tl.load(z + (indices_0[:, None, None] * z_stride_0 + indices_2[None, :, None] * z_stride_1 + indices_3[None, None, :] * z_stride_2), mask_2[None, :, None] & mask_3[None, None, :], other=0)
        subscript_4 = load_4[:, None, :, :]
        # src[_semiring_helion.py:128]: w
        # src[_semiring_helion.py:129]: * y[tile_p, tile_i, tile_k][:, :, None, :]
        # src[_semiring_helion.py:130]: * z[tile_p, tile_j, tile_k][:, None, :, :],
        v_6 = v_5 * subscript_4
        # src[_semiring_helion.py:127]: acc = acc + torch.sum(
        # src[_semiring_helion.py:128]:     w
        # src[_semiring_helion.py:129]:     * y[tile_p, tile_i, tile_k][:, :, None, :]
        # src[_semiring_helion.py:127-132]: ...
        sum_1 = tl.cast(tl.sum(v_6, 3), tl.float32)
        acc = acc_copy_0 + sum_1
    # src[_semiring_helion.py:133]: out[tile_p, tile_i, tile_j] = acc * x[tile_p, tile_i, tile_j]
    load_5 = tl.load(x + (indices_0[:, None, None] * x_stride_0 + indices_1[None, :, None] * x_stride_1 + indices_2[None, None, :] * x_stride_2), mask_1[None, :, None] & mask_2[None, None, :], other=0)
    v_8 = acc * load_5
    tl.store(out + (indices_0[:, None, None] * out_stride_0 + indices_1[None, :, None] * out_stride_1 + indices_2[None, None, :] * out_stride_2), v_8, mask_1[None, :, None] & mask_2[None, None, :])

def __contract_over_k_c1(a: Tensor, b: Tensor, c: Tensor, x: Tensor, y: Tensor, z: Tensor, is_max: hl.constexpr, *, _launcher=_default_launcher):
    """R[p, i, j] = x[p, i, j] sum_k W y[p, i, k] z[p, j, k]."""
    # src[_semiring_helion.py:113]: n_p, n_i, n_j = a.shape
    n_p, n_i, n_j = a.shape
    # src[_semiring_helion.py:114]: n_k = b.size(-1)
    n_k = b.size(-1)
    # src[_semiring_helion.py:115]: out = torch.empty_like(a)
    out = torch.empty_like(a)
    # src[_semiring_helion.py:116]: for tile_p, tile_i, tile_j in hl.tile([n_p, n_i, n_j]):
    _BLOCK_SIZE_1_c1 = 16
    _BLOCK_SIZE_2_c1 = 16
    # src[_semiring_helion.py:116]: for tile_p, tile_i, tile_j in hl.tile([n_p, n_i, n_j]):
    # src[_semiring_helion.py:117]:     acc = hl.zeros([tile_p, tile_i, tile_j], dtype=a.dtype)
    # src[_semiring_helion.py:118]:     for tile_k in hl.tile(n_k):
    # src[_semiring_helion.py:116-133]: ...
    _launcher(_helion__contract_over_k_c1, (n_p * ((n_i + _BLOCK_SIZE_1_c1 - 1) // _BLOCK_SIZE_1_c1) * ((n_j + _BLOCK_SIZE_2_c1 - 1) // _BLOCK_SIZE_2_c1),), c, a, b, y, z, x, out, a.stride(0), a.stride(1), a.stride(2), b.stride(0), b.stride(1), b.stride(2), c.stride(0), c.stride(1), c.stride(2), out.stride(0), out.stride(1), out.stride(2), x.stride(0), x.stride(1), x.stride(2), y.stride(0), y.stride(1), y.stride(2), z.stride(0), z.stride(1), z.stride(2), n_i, n_j, n_p, n_k, num_warps=2, num_stages=1)
    # src[_semiring_helion.py:134]: return out
    return out

# =================================================================
# Config 2
# =================================================================

_BLOCK_SIZE_1_c2 = tl.constexpr(64)
_BLOCK_SIZE_2_c2 = tl.constexpr(16)
_BLOCK_SIZE_0_c2 = tl.constexpr(1)

@triton.jit
def _helion__contract_over_k_c2(c, a, b, y, z, x, out, a_stride_0, a_stride_1, a_stride_2, b_stride_0, b_stride_1, b_stride_2, c_stride_0, c_stride_1, c_stride_2, out_stride_0, out_stride_1, out_stride_2, x_stride_0, x_stride_1, x_stride_2, y_stride_0, y_stride_1, y_stride_2, z_stride_0, z_stride_1, z_stride_2, n_i, n_j, n_p, n_k):
    # src[_semiring_helion.py:116]: for tile_p, tile_i, tile_j in hl.tile([n_p, n_i, n_j]):
    num_blocks_0 = n_p
    num_blocks_1 = tl.cdiv(n_i, _BLOCK_SIZE_1_c2)
    pid_0 = tl.program_id(0) % num_blocks_0
    pid_1 = tl.program_id(0) // num_blocks_0 % num_blocks_1
    pid_2 = tl.program_id(0) // (num_blocks_0 * num_blocks_1)
    offset_0 = pid_0
    indices_0 = offset_0 + tl.zeros([1], tl.int32)
    offset_1 = pid_1 * _BLOCK_SIZE_1_c2
    indices_1 = (offset_1 + tl.arange(0, _BLOCK_SIZE_1_c2)).to(tl.int32)
    mask_1 = indices_1 < n_i
    offset_2 = pid_2 * _BLOCK_SIZE_2_c2
    indices_2 = (offset_2 + tl.arange(0, _BLOCK_SIZE_2_c2)).to(tl.int32)
    mask_2 = indices_2 < n_j
    # src[_semiring_helion.py:117]: acc = hl.zeros([tile_p, tile_i, tile_j], dtype=a.dtype)
    acc = tl.full([_BLOCK_SIZE_0_c2, _BLOCK_SIZE_1_c2, _BLOCK_SIZE_2_c2], 0.0, tl.float32)
    # src[_semiring_helion.py:118]: for tile_k in hl.tile(n_k):
    # src[_semiring_helion.py:119]:     cc = c[tile_p, tile_i, tile_k][:, :, None, :]
    # src[_semiring_helion.py:120]:     terms = (
    # src[_semiring_helion.py:118-132]: ...
    for offset_3 in tl.range(0, tl.cast(n_k, tl.int32), disallow_acc_multi_buffer=True):
        indices_3 = offset_3 + tl.arange(0, 1).to(tl.int32)
        acc_copy = acc
        acc_copy_0 = acc_copy
        # src[_semiring_helion.py:119]: cc = c[tile_p, tile_i, tile_k][:, :, None, :]
        load = tl.load(c + (indices_0[:, None, None] * c_stride_0 + indices_1[None, :, None] * c_stride_1 + indices_3[None, None, :] * c_stride_2), mask_1[None, :, None], other=0)
        cc = load[:, :, None, :]
        # src[_semiring_helion.py:121]: a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
        load_1 = tl.load(a + (indices_0[:, None, None] * a_stride_0 + indices_1[None, :, None] * a_stride_1 + indices_2[None, None, :] * a_stride_2), mask_1[None, :, None] & mask_2[None, None, :], other=0)
        subscript_1 = load_1[:, :, :, None]
        load_2 = tl.load(b + (indices_0[:, None, None] * b_stride_0 + indices_2[None, :, None] * b_stride_1 + indices_3[None, None, :] * b_stride_2), mask_2[None, :, None], other=0)
        subscript_2 = load_2[:, None, :, :]
        v_0 = subscript_1 + subscript_2
        # src[_semiring_helion.py:126]: w = torch.where(cc == float("-inf"), 0.0, torch.exp(terms - cc))
        v_1 = tl.full([], float('-inf'), tl.float32)
        v_2 = cc == v_1
        v_3 = v_0 - cc
        v_4 = libdevice.exp(v_3)
        scalar_tensor = tl.full([], 0.0, tl.float32)
        where = tl.where(v_2, scalar_tensor, v_4)
        # src[_semiring_helion.py:129]: * y[tile_p, tile_i, tile_k][:, :, None, :]
        load_3 = tl.load(y + (indices_0[:, None, None] * y_stride_0 + indices_1[None, :, None] * y_stride_1 + indices_3[None, None, :] * y_stride_2), mask_1[None, :, None], other=0)
        subscript_3 = load_3[:, :, None, :]
        # src[_semiring_helion.py:128]: w
        # src[_semiring_helion.py:129]: * y[tile_p, tile_i, tile_k][:, :, None, :]
        v_5 = where * subscript_3
        # src[_semiring_helion.py:130]: * z[tile_p, tile_j, tile_k][:, None, :, :],
        load_4 = tl.load(z + (indices_0[:, None, None] * z_stride_0 + indices_2[None, :, None] * z_stride_1 + indices_3[None, None, :] * z_stride_2), mask_2[None, :, None], other=0)
        subscript_4 = load_4[:, None, :, :]
        # src[_semiring_helion.py:128]: w
        # src[_semiring_helion.py:129]: * y[tile_p, tile_i, tile_k][:, :, None, :]
        # src[_semiring_helion.py:130]: * z[tile_p, tile_j, tile_k][:, None, :, :],
        v_6 = v_5 * subscript_4
        # src[_semiring_helion.py:127]: acc = acc + torch.sum(
        # src[_semiring_helion.py:128]:     w
        # src[_semiring_helion.py:129]:     * y[tile_p, tile_i, tile_k][:, :, None, :]
        # src[_semiring_helion.py:127-132]: ...
        sum_1 = tl.cast(tl.sum(v_6, 3), tl.float32)
        acc = acc_copy_0 + sum_1
    # src[_semiring_helion.py:133]: out[tile_p, tile_i, tile_j] = acc * x[tile_p, tile_i, tile_j]
    load_5 = tl.load(x + (indices_0[:, None, None] * x_stride_0 + indices_1[None, :, None] * x_stride_1 + indices_2[None, None, :] * x_stride_2), mask_1[None, :, None] & mask_2[None, None, :], other=0)
    v_8 = acc * load_5
    tl.store(out + (indices_0[:, None, None] * out_stride_0 + indices_1[None, :, None] * out_stride_1 + indices_2[None, None, :] * out_stride_2), v_8, mask_1[None, :, None] & mask_2[None, None, :])

def __contract_over_k_c2(a: Tensor, b: Tensor, c: Tensor, x: Tensor, y: Tensor, z: Tensor, is_max: hl.constexpr, *, _launcher=_default_launcher):
    """R[p, i, j] = x[p, i, j] sum_k W y[p, i, k] z[p, j, k]."""
    # src[_semiring_helion.py:113]: n_p, n_i, n_j = a.shape
    n_p, n_i, n_j = a.shape
    # src[_semiring_helion.py:114]: n_k = b.size(-1)
    n_k = b.size(-1)
    # src[_semiring_helion.py:115]: out = torch.empty_like(a)
    out = torch.empty_like(a)
    # src[_semiring_helion.py:116]: for tile_p, tile_i, tile_j in hl.tile([n_p, n_i, n_j]):
    _BLOCK_SIZE_1_c2 = 64
    _BLOCK_SIZE_2_c2 = 16
    # src[_semiring_helion.py:116]: for tile_p, tile_i, tile_j in hl.tile([n_p, n_i, n_j]):
    # src[_semiring_helion.py:117]:     acc = hl.zeros([tile_p, tile_i, tile_j], dtype=a.dtype)
    # src[_semiring_helion.py:118]:     for tile_k in hl.tile(n_k):
    # src[_semiring_helion.py:116-133]: ...
    _launcher(_helion__contract_over_k_c2, (n_p * ((n_i + _BLOCK_SIZE_1_c2 - 1) // _BLOCK_SIZE_1_c2) * ((n_j + _BLOCK_SIZE_2_c2 - 1) // _BLOCK_SIZE_2_c2),), c, a, b, y, z, x, out, a.stride(0), a.stride(1), a.stride(2), b.stride(0), b.stride(1), b.stride(2), c.stride(0), c.stride(1), c.stride(2), out.stride(0), out.stride(1), out.stride(2), x.stride(0), x.stride(1), x.stride(2), y.stride(0), y.stride(1), y.stride(2), z.stride(0), z.stride(1), z.stride(2), n_i, n_j, n_p, n_k, num_warps=2, num_stages=1)
    # src[_semiring_helion.py:134]: return out
    return out

# =================================================================
# Heuristic dispatch
# =================================================================

# === Kernel: _max_bmm_kernel ===


# === Kernel: _contract_over_i ===


# === Kernel: _contract_over_j ===


# === Kernel: _contract_over_k ===


def key__contract_over_k(*args) -> int:
    _arg0_dim0 = int(args[0].shape[0]) if len(args) > 0 and isinstance(args[0], torch.Tensor) and args[0].ndim > 0 else 0
    _arg0_dim1 = int(args[0].shape[1]) if len(args) > 0 and isinstance(args[0], torch.Tensor) and args[0].ndim > 1 else 0
    _arg6_scalar = args[6] if len(args) > 6 and isinstance(args[6], (int, float)) else 0
    if _arg0_dim1 <= 32.0:
        if _arg0_dim0 <= 256.0:
            if _arg0_dim0 <= 64.0:
                return 1
            else:
                if _arg6_scalar <= 0.0:
                    return 0
                else:
                    return 1
        else:
            return 0
    else:
        return 2



def _contract_over_k(*args, **kwargs):
    return [
        __contract_over_k_c0,
        __contract_over_k_c1,
        __contract_over_k_c2,
    ][key__contract_over_k(*args)](*args, **kwargs)
