# Generated by scripts/helion_aot.py; do not edit.
# ruff: noqa
# fmt: off
# Auto-generated standalone Triton kernel for '_dag_forward_kernel'.
# No Helion dependency required at runtime.

from __future__ import annotations

import torch
import triton
import triton.language as tl


def _default_launcher(
    triton_kernel,
    grid,
    *args,
    num_warps,
    num_stages,
    launch_cooperative_grid=False,
    **kwargs,
):
    return triton_kernel.run(
        *args,
        grid=grid,
        warmup=False,
        num_warps=num_warps,
        num_stages=num_stages,
        launch_cooperative_grid=launch_cooperative_grid,
        **kwargs,
    )


# =================================================================
# Config 0
# =================================================================

_BLOCK_SIZE_0_c0 = tl.constexpr(1)

@triton.jit
def _compose_affine_0(param_0, param_1, param_2, param_3, param_4, param_5, param_6, param_7):
    # src[_dtw_helion.py:177]: z_left = hl.associative_scan(_compose_affine, (a, b, identity_a, identity_b), dim=1)[3]
    v_0 = param_4 * param_0
    v_1 = param_4 * param_1
    v_2 = v_1 + param_5
    v_3 = param_6 * param_0
    v_4 = param_6 * param_1
    v_5 = v_4 + param_7
    # src[_dtw_helion.py:163]: def _dag_forward_kernel(
    # src[_dtw_helion.py:164]:     w_down: Tensor, w_right_next: Tensor, w_diag_next: Tensor, x: Tensor
    # src[_dtw_helion.py:165]: ) -> Tensor:
    # src[_dtw_helion.py:163-180]: ...
    return (v_0, v_2, v_3, v_5)

@triton.jit
def _helion__dag_forward_kernel_c0(w_down, x, w_right_next, w_diag_next, y, w_down_size_2, w_diag_next_stride_0, w_diag_next_stride_1, w_diag_next_stride_2, w_down_stride_0, w_down_stride_1, w_down_stride_2, w_right_next_stride_0, w_right_next_stride_1, w_right_next_stride_2, x_stride_0, x_stride_1, x_stride_2, y_stride_0, y_stride_1, y_stride_2, R, _RDIM_SIZE_1: tl.constexpr):
    # src[_dtw_helion.py:169]: for tile_b in hl.tile(B, block_size=1):
    pid_0 = tl.program_id(0)
    offset_0 = pid_0
    indices_0 = offset_0 + tl.zeros([1], tl.int32)
    indices_1 = tl.arange(0, _RDIM_SIZE_1).to(tl.int32)
    mask_1 = indices_1 < w_down_size_2
    # src[_dtw_helion.py:170]: y_prev = torch.zeros_like(x[tile_b, 0, :])
    load = tl.load(x + (indices_0[:, None] * x_stride_0 + 0 * x_stride_1 + (0 + indices_1)[None, :] * x_stride_2), mask_1[None, :], other=0)
    y_prev = tl.full([_BLOCK_SIZE_0_c0, _RDIM_SIZE_1], 0, tl.float64)
    # src[_dtw_helion.py:171]: for i in hl.grid(R):
    # src[_dtw_helion.py:172]:     base = x[tile_b, i, :] + w_down[tile_b, i, :] * y_prev
    # src[_dtw_helion.py:173]:     a = w_right_next[tile_b, i, :]
    # src[_dtw_helion.py:171-179]: ...
    for offset_2 in tl.range(0, tl.cast(R, tl.int32), loop_unroll_factor=4, num_stages=3):
        y_prev_copy = y_prev
        y_prev_copy_0 = y_prev_copy
        # src[_dtw_helion.py:172]: base = x[tile_b, i, :] + w_down[tile_b, i, :] * y_prev
        load_1 = tl.load(x + (indices_0[:, None] * x_stride_0 + offset_2 * x_stride_1 + (0 + indices_1)[None, :] * x_stride_2), mask_1[None, :], other=0)
        load_2 = tl.load(w_down + (indices_0[:, None] * w_down_stride_0 + offset_2 * w_down_stride_1 + (0 + indices_1)[None, :] * w_down_stride_2), mask_1[None, :], other=0)
        v_0 = load_2 * y_prev_copy_0
        v_1 = load_1 + v_0
        # src[_dtw_helion.py:173]: a = w_right_next[tile_b, i, :]
        load_3 = tl.load(w_right_next + (indices_0[:, None] * w_right_next_stride_0 + offset_2 * w_right_next_stride_1 + (0 + indices_1)[None, :] * w_right_next_stride_2), mask_1[None, :], other=0)
        # src[_dtw_helion.py:174]: b = a * base + w_diag_next[tile_b, i, :] * y_prev
        v_2 = load_3 * v_1
        load_4 = tl.load(w_diag_next + (indices_0[:, None] * w_diag_next_stride_0 + offset_2 * w_diag_next_stride_1 + (0 + indices_1)[None, :] * w_diag_next_stride_2), mask_1[None, :], other=0)
        v_3 = load_4 * y_prev_copy_0
        v_4 = v_2 + v_3
        # src[_dtw_helion.py:175]: identity_a = torch.ones_like(b)
        identity_a = tl.full([_BLOCK_SIZE_0_c0, _RDIM_SIZE_1], 1, tl.float64)
        # src[_dtw_helion.py:176]: identity_b = torch.zeros_like(b)
        identity_b = tl.full([_BLOCK_SIZE_0_c0, _RDIM_SIZE_1], 0, tl.float64)
        # src[_dtw_helion.py:177]: z_left = hl.associative_scan(_compose_affine, (a, b, identity_a, identity_b), dim=1)[3]
        z_left = tl.associative_scan((load_3, v_4, identity_a, identity_b), 1, _compose_affine_0)[3]
        # src[_dtw_helion.py:178]: y_prev = base + z_left
        y_prev = v_1 + z_left
        # src[_dtw_helion.py:179]: y[tile_b, i, :] = y_prev
        tl.store(y + (indices_0[:, None] * y_stride_0 + offset_2 * y_stride_1 + (0 + indices_1)[None, :] * y_stride_2), y_prev, mask_1[None, :])

def __dag_forward_kernel_c0(w_down: Tensor, w_right_next: Tensor, w_diag_next: Tensor, x: Tensor, *, _launcher=_default_launcher):
    """y of the forward accumulation; the *_next weights are taken at column j + 1."""
    # src[_dtw_helion.py:167]: B, R, L = x.shape
    B, R, L = x.shape
    # src[_dtw_helion.py:168]: y = torch.empty_like(x)
    y = torch.empty_like(x)
    # src[_dtw_helion.py:169]: for tile_b in hl.tile(B, block_size=1):
    _RDIM_SIZE_1 = triton.next_power_of_2(w_down.size(2))
    # src[_dtw_helion.py:169]: for tile_b in hl.tile(B, block_size=1):
    # src[_dtw_helion.py:170]:     y_prev = torch.zeros_like(x[tile_b, 0, :])
    # src[_dtw_helion.py:171]:     for i in hl.grid(R):
    # src[_dtw_helion.py:169-179]: ...
    _launcher(_helion__dag_forward_kernel_c0, (B,), w_down, x, w_right_next, w_diag_next, y, w_down.size(2), w_diag_next.stride(0), w_diag_next.stride(1), w_diag_next.stride(2), w_down.stride(0), w_down.stride(1), w_down.stride(2), w_right_next.stride(0), w_right_next.stride(1), w_right_next.stride(2), x.stride(0), x.stride(1), x.stride(2), y.stride(0), y.stride(1), y.stride(2), R, _RDIM_SIZE_1, num_warps=1, num_stages=2)
    # src[_dtw_helion.py:180]: return y
    return y

# =================================================================
# Config 1
# =================================================================

_BLOCK_SIZE_0_c1 = tl.constexpr(1)

@triton.jit
def _compose_affine_0(param_0, param_1, param_2, param_3, param_4, param_5, param_6, param_7):
    # src[_dtw_helion.py:177]: z_left = hl.associative_scan(_compose_affine, (a, b, identity_a, identity_b), dim=1)[3]
    v_0 = param_4 * param_0
    v_1 = param_4 * param_1
    v_2 = v_1 + param_5
    v_3 = param_6 * param_0
    v_4 = param_6 * param_1
    v_5 = v_4 + param_7
    # src[_dtw_helion.py:163]: def _dag_forward_kernel(
    # src[_dtw_helion.py:164]:     w_down: Tensor, w_right_next: Tensor, w_diag_next: Tensor, x: Tensor
    # src[_dtw_helion.py:165]: ) -> Tensor:
    # src[_dtw_helion.py:163-180]: ...
    return (v_0, v_2, v_3, v_5)

@triton.jit
def _helion__dag_forward_kernel_c1(w_down, x, w_right_next, w_diag_next, y, w_down_size_2, w_diag_next_stride_0, w_diag_next_stride_1, w_diag_next_stride_2, w_down_stride_0, w_down_stride_1, w_down_stride_2, w_right_next_stride_0, w_right_next_stride_1, w_right_next_stride_2, x_stride_0, x_stride_1, x_stride_2, y_stride_0, y_stride_1, y_stride_2, R, _RDIM_SIZE_1: tl.constexpr):
    # src[_dtw_helion.py:169]: for tile_b in hl.tile(B, block_size=1):
    pid_0 = tl.program_id(0)
    offset_0 = pid_0
    indices_0 = offset_0 + tl.zeros([1], tl.int32)
    indices_1 = tl.arange(0, _RDIM_SIZE_1).to(tl.int32)
    mask_1 = indices_1 < w_down_size_2
    # src[_dtw_helion.py:170]: y_prev = torch.zeros_like(x[tile_b, 0, :])
    load = tl.load(x + (indices_0[:, None] * x_stride_0 + 0 * x_stride_1 + (0 + indices_1)[None, :] * x_stride_2), mask_1[None, :], other=0)
    y_prev = tl.full([_BLOCK_SIZE_0_c1, _RDIM_SIZE_1], 0, tl.float64)
    # src[_dtw_helion.py:171]: for i in hl.grid(R):
    # src[_dtw_helion.py:172]:     base = x[tile_b, i, :] + w_down[tile_b, i, :] * y_prev
    # src[_dtw_helion.py:173]:     a = w_right_next[tile_b, i, :]
    # src[_dtw_helion.py:171-179]: ...
    for offset_2 in tl.range(0, tl.cast(R, tl.int32), flatten=True):
        y_prev_copy = y_prev
        y_prev_copy_0 = y_prev_copy
        # src[_dtw_helion.py:172]: base = x[tile_b, i, :] + w_down[tile_b, i, :] * y_prev
        load_1 = tl.load(x + (indices_0[:, None] * x_stride_0 + offset_2 * x_stride_1 + (0 + indices_1)[None, :] * x_stride_2), mask_1[None, :], other=0)
        load_2 = tl.load(w_down + (indices_0[:, None] * w_down_stride_0 + offset_2 * w_down_stride_1 + (0 + indices_1)[None, :] * w_down_stride_2), mask_1[None, :], other=0)
        v_0 = load_2 * y_prev_copy_0
        v_1 = load_1 + v_0
        # src[_dtw_helion.py:173]: a = w_right_next[tile_b, i, :]
        load_3 = tl.load(w_right_next + (indices_0[:, None] * w_right_next_stride_0 + offset_2 * w_right_next_stride_1 + (0 + indices_1)[None, :] * w_right_next_stride_2), mask_1[None, :], other=0)
        # src[_dtw_helion.py:174]: b = a * base + w_diag_next[tile_b, i, :] * y_prev
        v_2 = load_3 * v_1
        load_4 = tl.load(w_diag_next + (indices_0[:, None] * w_diag_next_stride_0 + offset_2 * w_diag_next_stride_1 + (0 + indices_1)[None, :] * w_diag_next_stride_2), mask_1[None, :], other=0)
        v_3 = load_4 * y_prev_copy_0
        v_4 = v_2 + v_3
        # src[_dtw_helion.py:175]: identity_a = torch.ones_like(b)
        identity_a = tl.full([_BLOCK_SIZE_0_c1, _RDIM_SIZE_1], 1, tl.float64)
        # src[_dtw_helion.py:176]: identity_b = torch.zeros_like(b)
        identity_b = tl.full([_BLOCK_SIZE_0_c1, _RDIM_SIZE_1], 0, tl.float64)
        # src[_dtw_helion.py:177]: z_left = hl.associative_scan(_compose_affine, (a, b, identity_a, identity_b), dim=1)[3]
        z_left = tl.associative_scan((load_3, v_4, identity_a, identity_b), 1, _compose_affine_0)[3]
        # src[_dtw_helion.py:178]: y_prev = base + z_left
        y_prev = v_1 + z_left
        # src[_dtw_helion.py:179]: y[tile_b, i, :] = y_prev
        tl.store(y + (indices_0[:, None] * y_stride_0 + offset_2 * y_stride_1 + (0 + indices_1)[None, :] * y_stride_2), y_prev, mask_1[None, :])

def __dag_forward_kernel_c1(w_down: Tensor, w_right_next: Tensor, w_diag_next: Tensor, x: Tensor, *, _launcher=_default_launcher):
    """y of the forward accumulation; the *_next weights are taken at column j + 1."""
    # src[_dtw_helion.py:167]: B, R, L = x.shape
    B, R, L = x.shape
    # src[_dtw_helion.py:168]: y = torch.empty_like(x)
    y = torch.empty_like(x)
    # src[_dtw_helion.py:169]: for tile_b in hl.tile(B, block_size=1):
    _RDIM_SIZE_1 = triton.next_power_of_2(w_down.size(2))
    # src[_dtw_helion.py:169]: for tile_b in hl.tile(B, block_size=1):
    # src[_dtw_helion.py:170]:     y_prev = torch.zeros_like(x[tile_b, 0, :])
    # src[_dtw_helion.py:171]:     for i in hl.grid(R):
    # src[_dtw_helion.py:169-179]: ...
    _launcher(_helion__dag_forward_kernel_c1, (B,), w_down, x, w_right_next, w_diag_next, y, w_down.size(2), w_diag_next.stride(0), w_diag_next.stride(1), w_diag_next.stride(2), w_down.stride(0), w_down.stride(1), w_down.stride(2), w_right_next.stride(0), w_right_next.stride(1), w_right_next.stride(2), x.stride(0), x.stride(1), x.stride(2), y.stride(0), y.stride(1), y.stride(2), R, _RDIM_SIZE_1, num_warps=32, num_stages=1)
    # src[_dtw_helion.py:180]: return y
    return y

# =================================================================
# Config 2
# =================================================================

_BLOCK_SIZE_0_c2 = tl.constexpr(1)

@triton.jit
def _compose_affine_0(param_0, param_1, param_2, param_3, param_4, param_5, param_6, param_7):
    # src[_dtw_helion.py:177]: z_left = hl.associative_scan(_compose_affine, (a, b, identity_a, identity_b), dim=1)[3]
    v_0 = param_4 * param_0
    v_1 = param_4 * param_1
    v_2 = v_1 + param_5
    v_3 = param_6 * param_0
    v_4 = param_6 * param_1
    v_5 = v_4 + param_7
    # src[_dtw_helion.py:163]: def _dag_forward_kernel(
    # src[_dtw_helion.py:164]:     w_down: Tensor, w_right_next: Tensor, w_diag_next: Tensor, x: Tensor
    # src[_dtw_helion.py:165]: ) -> Tensor:
    # src[_dtw_helion.py:163-180]: ...
    return (v_0, v_2, v_3, v_5)

@triton.jit
def _helion__dag_forward_kernel_c2(w_down, x, w_right_next, w_diag_next, y, w_down_size_2, w_diag_next_stride_0, w_diag_next_stride_1, w_diag_next_stride_2, w_down_stride_0, w_down_stride_1, w_down_stride_2, w_right_next_stride_0, w_right_next_stride_1, w_right_next_stride_2, x_stride_0, x_stride_1, x_stride_2, y_stride_0, y_stride_1, y_stride_2, R, _RDIM_SIZE_1: tl.constexpr):
    # src[_dtw_helion.py:169]: for tile_b in hl.tile(B, block_size=1):
    pid_0 = tl.program_id(0)
    offset_0 = pid_0
    indices_0 = offset_0 + tl.zeros([1], tl.int32)
    indices_1 = tl.arange(0, _RDIM_SIZE_1).to(tl.int32)
    mask_1 = indices_1 < w_down_size_2
    # src[_dtw_helion.py:170]: y_prev = torch.zeros_like(x[tile_b, 0, :])
    load = tl.load(x + (indices_0[:, None] * x_stride_0 + 0 * x_stride_1 + (0 + indices_1)[None, :] * x_stride_2), mask_1[None, :], other=0)
    y_prev = tl.full([_BLOCK_SIZE_0_c2, _RDIM_SIZE_1], 0, tl.float64)
    # src[_dtw_helion.py:171]: for i in hl.grid(R):
    # src[_dtw_helion.py:172]:     base = x[tile_b, i, :] + w_down[tile_b, i, :] * y_prev
    # src[_dtw_helion.py:173]:     a = w_right_next[tile_b, i, :]
    # src[_dtw_helion.py:171-179]: ...
    for offset_2 in tl.range(0, tl.cast(R, tl.int32), disallow_acc_multi_buffer=False, flatten=True):
        y_prev_copy = y_prev
        y_prev_copy_0 = y_prev_copy
        # src[_dtw_helion.py:172]: base = x[tile_b, i, :] + w_down[tile_b, i, :] * y_prev
        load_1 = tl.load(x + (indices_0[:, None] * x_stride_0 + offset_2 * x_stride_1 + (0 + indices_1)[None, :] * x_stride_2), mask_1[None, :], other=0)
        load_2 = tl.load(w_down + (indices_0[:, None] * w_down_stride_0 + offset_2 * w_down_stride_1 + (0 + indices_1)[None, :] * w_down_stride_2), mask_1[None, :], other=0)
        v_0 = load_2 * y_prev_copy_0
        v_1 = load_1 + v_0
        # src[_dtw_helion.py:173]: a = w_right_next[tile_b, i, :]
        load_3 = tl.load(w_right_next + (indices_0[:, None] * w_right_next_stride_0 + offset_2 * w_right_next_stride_1 + (0 + indices_1)[None, :] * w_right_next_stride_2), mask_1[None, :], other=0)
        # src[_dtw_helion.py:174]: b = a * base + w_diag_next[tile_b, i, :] * y_prev
        v_2 = load_3 * v_1
        load_4 = tl.load(w_diag_next + (indices_0[:, None] * w_diag_next_stride_0 + offset_2 * w_diag_next_stride_1 + (0 + indices_1)[None, :] * w_diag_next_stride_2), mask_1[None, :], other=0)
        v_3 = load_4 * y_prev_copy_0
        v_4 = v_2 + v_3
        # src[_dtw_helion.py:175]: identity_a = torch.ones_like(b)
        identity_a = tl.full([_BLOCK_SIZE_0_c2, _RDIM_SIZE_1], 1, tl.float64)
        # src[_dtw_helion.py:176]: identity_b = torch.zeros_like(b)
        identity_b = tl.full([_BLOCK_SIZE_0_c2, _RDIM_SIZE_1], 0, tl.float64)
        # src[_dtw_helion.py:177]: z_left = hl.associative_scan(_compose_affine, (a, b, identity_a, identity_b), dim=1)[3]
        z_left = tl.associative_scan((load_3, v_4, identity_a, identity_b), 1, _compose_affine_0)[3]
        # src[_dtw_helion.py:178]: y_prev = base + z_left
        y_prev = v_1 + z_left
        # src[_dtw_helion.py:179]: y[tile_b, i, :] = y_prev
        tl.store(y + (indices_0[:, None] * y_stride_0 + offset_2 * y_stride_1 + (0 + indices_1)[None, :] * y_stride_2), y_prev, mask_1[None, :])

def __dag_forward_kernel_c2(w_down: Tensor, w_right_next: Tensor, w_diag_next: Tensor, x: Tensor, *, _launcher=_default_launcher):
    """y of the forward accumulation; the *_next weights are taken at column j + 1."""
    # src[_dtw_helion.py:167]: B, R, L = x.shape
    B, R, L = x.shape
    # src[_dtw_helion.py:168]: y = torch.empty_like(x)
    y = torch.empty_like(x)
    # src[_dtw_helion.py:169]: for tile_b in hl.tile(B, block_size=1):
    _RDIM_SIZE_1 = triton.next_power_of_2(w_down.size(2))
    # src[_dtw_helion.py:169]: for tile_b in hl.tile(B, block_size=1):
    # src[_dtw_helion.py:170]:     y_prev = torch.zeros_like(x[tile_b, 0, :])
    # src[_dtw_helion.py:171]:     for i in hl.grid(R):
    # src[_dtw_helion.py:169-179]: ...
    _launcher(_helion__dag_forward_kernel_c2, (B,), w_down, x, w_right_next, w_diag_next, y, w_down.size(2), w_diag_next.stride(0), w_diag_next.stride(1), w_diag_next.stride(2), w_down.stride(0), w_down.stride(1), w_down.stride(2), w_right_next.stride(0), w_right_next.stride(1), w_right_next.stride(2), x.stride(0), x.stride(1), x.stride(2), y.stride(0), y.stride(1), y.stride(2), R, _RDIM_SIZE_1, num_warps=16, num_stages=3)
    # src[_dtw_helion.py:180]: return y
    return y

# =================================================================
# Heuristic dispatch
# =================================================================

# === Kernel: _dag_forward_kernel ===


def key__dag_forward_kernel(*args) -> int:
    _arg0_dim2 = int(args[0].shape[2]) if len(args) > 0 and isinstance(args[0], torch.Tensor) and args[0].ndim > 2 else 0
    if _arg0_dim2 <= 512.0:
        return 0
    else:
        if _arg0_dim2 <= 2048.0:
            return 2
        else:
            return 1



def _dag_forward_kernel(*args, **kwargs):
    return [
        __dag_forward_kernel_c0,
        __dag_forward_kernel_c1,
        __dag_forward_kernel_c2,
    ][key__dag_forward_kernel(*args)](*args, **kwargs)
