# Generated by scripts/helion_aot.py; do not edit.
# ruff: noqa
# fmt: off
# Auto-generated standalone Triton kernel for '_dtw_dp_kernel'.
# No Helion dependency required at runtime.

from __future__ import annotations

from torch._inductor.runtime import triton_helpers
from torch._inductor.runtime.triton_compat import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
import torch
import triton
import triton.language as tl


def _default_launcher(
    triton_kernel,
    grid,
    *args,
    num_warps,
    num_stages,
    launch_cooperative_grid=False,
    **kwargs,
):
    return triton_kernel.run(
        *args,
        grid=grid,
        warmup=False,
        num_warps=num_warps,
        num_stages=num_stages,
        launch_cooperative_grid=launch_cooperative_grid,
        **kwargs,
    )


def _get_num_sm(device, reserved_sms=0):
    if device.type == "cuda":
        available = torch.cuda.get_device_properties(device.index).multi_processor_count
    elif device.type == "xpu":
        available = torch.xpu.get_device_properties(device.index).gpu_subslice_count
    else:
        raise NotImplementedError(f"_get_num_sm not implemented for {device.type}")
    if reserved_sms <= 0:
        return available
    return max(available - reserved_sms, 1)


# =================================================================
# Config 0
# =================================================================

@triton.jit
def add_0(param_0, param_1):
    # src[_dtw_helion.py:131]: prev = hl.cumsum(cost[tile_b, 0, :], dim=1)
    v_0 = param_0 + param_1
    # src[_dtw_helion.py:126]: def _dtw_dp_kernel(cost: Tensor, soft: hl.constexpr, diag: hl.constexpr) -> Tensor:
    # src[_dtw_helion.py:127]:     """D of cost (B, R, L), with steps up, left and, if ``diag``, up-left."""
    # src[_dtw_helion.py:128]:     B, R, L = cost.shape
    # src[_dtw_helion.py:126-159]: ...
    return v_0

@triton.jit
def _compose_softmin_plus_whole_1(param_0, param_1, param_2, param_3):
    # src[_dtw_helion.py:141]: prev = hl.associative_scan(_compose_softmin_plus_whole, (c + prev, c), dim=1)[0]
    v_0 = param_3 + param_0
    v_1 = triton_helpers.minimum(param_2, v_0)
    v_2 = param_2 - v_0
    v_3 = tl_math.abs(v_2)
    v_4 = -v_3
    v_5 = libdevice.exp(v_4)
    v_6 = tl.full([], 1.0, tl.float32)
    v_7 = v_5 + v_6
    v_8 = tl_math.log(v_7)
    v_9 = v_1 - v_8
    v_10 = param_3 + param_1
    # src[_dtw_helion.py:126]: def _dtw_dp_kernel(cost: Tensor, soft: hl.constexpr, diag: hl.constexpr) -> Tensor:
    # src[_dtw_helion.py:127]:     """D of cost (B, R, L), with steps up, left and, if ``diag``, up-left."""
    # src[_dtw_helion.py:128]:     B, R, L = cost.shape
    # src[_dtw_helion.py:126-159]: ...
    return (v_9, v_10)

@triton.jit
def _helion__dtw_dp_kernel_c0(cost, D, D_stride_0, D_stride_1, D_stride_2, cost_stride_0, cost_stride_1, cost_stride_2, B, L, R, _NUM_SM: tl.constexpr, _RDIM_SIZE_1: tl.constexpr):
    # src[_dtw_helion.py:130]: for tile_b in hl.tile(B, block_size=1):
    # src[_dtw_helion.py:131]:     prev = hl.cumsum(cost[tile_b, 0, :], dim=1)
    # src[_dtw_helion.py:132]:     D[tile_b, 0, :] = prev
    # src[_dtw_helion.py:130-158]: ...
    total_pids = B
    for virtual_pid in tl.range(tl.program_id(0), total_pids, _NUM_SM * 8, disallow_acc_multi_buffer=True):
        # src[_dtw_helion.py:130]: for tile_b in hl.tile(B, block_size=1):
        pid_0 = virtual_pid
        offset_0 = pid_0
        indices_0 = offset_0 + tl.zeros([1], tl.int32)
        indices_1 = tl.arange(0, _RDIM_SIZE_1).to(tl.int32)
        mask_1 = indices_1 < L
        # src[_dtw_helion.py:131]: prev = hl.cumsum(cost[tile_b, 0, :], dim=1)
        load = tl.load(cost + (indices_0[:, None] * cost_stride_0 + 0 * cost_stride_1 + (0 + indices_1)[None, :] * cost_stride_2), mask_1[None, :], other=0)
        prev = tl.associative_scan(load, 1, add_0)
        # src[_dtw_helion.py:132]: D[tile_b, 0, :] = prev
        tl.store(D + (indices_0[:, None] * D_stride_0 + 0 * D_stride_1 + (0 + indices_1)[None, :] * D_stride_2), prev, mask_1[None, :])
        # src[_dtw_helion.py:133]: for n in hl.grid(1, R):
        # src[_dtw_helion.py:134]:     c = cost[tile_b, n, :]
        # src[_dtw_helion.py:135]:     identity_a = torch.full_like(c, float("inf"))
        # src[_dtw_helion.py:133-158]: ...
        for offset_2 in tl.range(1, tl.cast(R, tl.int32), loop_unroll_factor=3, num_stages=3, flatten=True):
            prev_copy = prev
            prev_copy_0 = prev_copy
            # src[_dtw_helion.py:134]: c = cost[tile_b, n, :]
            c = tl.load(cost + (indices_0[:, None] * cost_stride_0 + offset_2 * cost_stride_1 + (0 + indices_1)[None, :] * cost_stride_2), mask_1[None, :], other=0)
            # src[_dtw_helion.py:141]: prev = hl.associative_scan(_compose_softmin_plus_whole, (c + prev, c), dim=1)[0]
            v_0 = c + prev_copy_0
            prev = tl.associative_scan((v_0, c), 1, _compose_softmin_plus_whole_1)[0]
            # src[_dtw_helion.py:158]: D[tile_b, n, :] = prev
            tl.store(D + (indices_0[:, None] * D_stride_0 + offset_2 * D_stride_1 + (0 + indices_1)[None, :] * D_stride_2), prev, mask_1[None, :])

def __dtw_dp_kernel_c0(cost: Tensor, soft: hl.constexpr, diag: hl.constexpr, *, _launcher=_default_launcher):
    """D of cost (B, R, L), with steps up, left and, if ``diag``, up-left."""
    # src[_dtw_helion.py:128]: B, R, L = cost.shape
    B, R, L = cost.shape
    # src[_dtw_helion.py:129]: D = torch.empty_like(cost)
    D = torch.empty_like(cost)
    # src[_dtw_helion.py:130]: for tile_b in hl.tile(B, block_size=1):
    _NUM_SM = _get_num_sm(cost.device)
    _RDIM_SIZE_1 = triton.next_power_of_2(L)
    # src[_dtw_helion.py:130]: for tile_b in hl.tile(B, block_size=1):
    # src[_dtw_helion.py:131]:     prev = hl.cumsum(cost[tile_b, 0, :], dim=1)
    # src[_dtw_helion.py:132]:     D[tile_b, 0, :] = prev
    # src[_dtw_helion.py:130-158]: ...
    _launcher(_helion__dtw_dp_kernel_c0, (_NUM_SM * 8,), cost, D, D.stride(0), D.stride(1), D.stride(2), cost.stride(0), cost.stride(1), cost.stride(2), B, L, R, _NUM_SM, _RDIM_SIZE_1, num_warps=16, num_stages=1)
    # src[_dtw_helion.py:159]: return D
    return D

# =================================================================
# Config 1
# =================================================================

@triton.jit
def add_0(param_0, param_1):
    # src[_dtw_helion.py:131]: prev = hl.cumsum(cost[tile_b, 0, :], dim=1)
    v_0 = param_0 + param_1
    # src[_dtw_helion.py:126]: def _dtw_dp_kernel(cost: Tensor, soft: hl.constexpr, diag: hl.constexpr) -> Tensor:
    # src[_dtw_helion.py:127]:     """D of cost (B, R, L), with steps up, left and, if ``diag``, up-left."""
    # src[_dtw_helion.py:128]:     B, R, L = cost.shape
    # src[_dtw_helion.py:126-159]: ...
    return v_0

@triton.jit
def _compose_softmin_plus_whole_1(param_0, param_1, param_2, param_3):
    # src[_dtw_helion.py:141]: prev = hl.associative_scan(_compose_softmin_plus_whole, (c + prev, c), dim=1)[0]
    v_0 = param_3 + param_0
    v_1 = triton_helpers.minimum(param_2, v_0)
    v_2 = param_2 - v_0
    v_3 = tl_math.abs(v_2)
    v_4 = -v_3
    v_5 = libdevice.exp(v_4)
    v_6 = tl.full([], 1.0, tl.float32)
    v_7 = v_5 + v_6
    v_8 = tl_math.log(v_7)
    v_9 = v_1 - v_8
    v_10 = param_3 + param_1
    # src[_dtw_helion.py:126]: def _dtw_dp_kernel(cost: Tensor, soft: hl.constexpr, diag: hl.constexpr) -> Tensor:
    # src[_dtw_helion.py:127]:     """D of cost (B, R, L), with steps up, left and, if ``diag``, up-left."""
    # src[_dtw_helion.py:128]:     B, R, L = cost.shape
    # src[_dtw_helion.py:126-159]: ...
    return (v_9, v_10)

@triton.jit
def _helion__dtw_dp_kernel_c1(cost, D, D_stride_0, D_stride_1, D_stride_2, cost_stride_0, cost_stride_1, cost_stride_2, L, R, _RDIM_SIZE_1: tl.constexpr):
    # src[_dtw_helion.py:130]: for tile_b in hl.tile(B, block_size=1):
    pid_0 = tl.program_id(0)
    offset_0 = pid_0
    indices_0 = offset_0 + tl.zeros([1], tl.int32)
    indices_1 = tl.arange(0, _RDIM_SIZE_1).to(tl.int32)
    mask_1 = indices_1 < L
    # src[_dtw_helion.py:131]: prev = hl.cumsum(cost[tile_b, 0, :], dim=1)
    load = tl.load(cost + (indices_0[:, None] * cost_stride_0 + 0 * cost_stride_1 + (0 + indices_1)[None, :] * cost_stride_2), mask_1[None, :], other=0)
    prev = tl.associative_scan(load, 1, add_0)
    # src[_dtw_helion.py:132]: D[tile_b, 0, :] = prev
    tl.store(D + (indices_0[:, None] * D_stride_0 + 0 * D_stride_1 + (0 + indices_1)[None, :] * D_stride_2), prev, mask_1[None, :])
    # src[_dtw_helion.py:133]: for n in hl.grid(1, R):
    # src[_dtw_helion.py:134]:     c = cost[tile_b, n, :]
    # src[_dtw_helion.py:135]:     identity_a = torch.full_like(c, float("inf"))
    # src[_dtw_helion.py:133-158]: ...
    for offset_2 in tl.range(1, tl.cast(R, tl.int32), num_stages=3, disallow_acc_multi_buffer=True):
        prev_copy = prev
        prev_copy_0 = prev_copy
        # src[_dtw_helion.py:134]: c = cost[tile_b, n, :]
        c = tl.load(cost + (indices_0[:, None] * cost_stride_0 + offset_2 * cost_stride_1 + (0 + indices_1)[None, :] * cost_stride_2), mask_1[None, :], other=0, eviction_policy='evict_last')
        # src[_dtw_helion.py:141]: prev = hl.associative_scan(_compose_softmin_plus_whole, (c + prev, c), dim=1)[0]
        v_0 = c + prev_copy_0
        prev = tl.associative_scan((v_0, c), 1, _compose_softmin_plus_whole_1)[0]
        # src[_dtw_helion.py:158]: D[tile_b, n, :] = prev
        tl.store(D + (indices_0[:, None] * D_stride_0 + offset_2 * D_stride_1 + (0 + indices_1)[None, :] * D_stride_2), prev, mask_1[None, :])

def __dtw_dp_kernel_c1(cost: Tensor, soft: hl.constexpr, diag: hl.constexpr, *, _launcher=_default_launcher):
    """D of cost (B, R, L), with steps up, left and, if ``diag``, up-left."""
    # src[_dtw_helion.py:128]: B, R, L = cost.shape
    B, R, L = cost.shape
    # src[_dtw_helion.py:129]: D = torch.empty_like(cost)
    D = torch.empty_like(cost)
    # src[_dtw_helion.py:130]: for tile_b in hl.tile(B, block_size=1):
    _RDIM_SIZE_1 = triton.next_power_of_2(L)
    # src[_dtw_helion.py:130]: for tile_b in hl.tile(B, block_size=1):
    # src[_dtw_helion.py:131]:     prev = hl.cumsum(cost[tile_b, 0, :], dim=1)
    # src[_dtw_helion.py:132]:     D[tile_b, 0, :] = prev
    # src[_dtw_helion.py:130-158]: ...
    _launcher(_helion__dtw_dp_kernel_c1, (B,), cost, D, D.stride(0), D.stride(1), D.stride(2), cost.stride(0), cost.stride(1), cost.stride(2), L, R, _RDIM_SIZE_1, num_warps=8, num_stages=1)
    # src[_dtw_helion.py:159]: return D
    return D

# =================================================================
# Config 2
# =================================================================

@triton.jit
def add_0(param_0, param_1):
    # src[_dtw_helion.py:131]: prev = hl.cumsum(cost[tile_b, 0, :], dim=1)
    v_0 = param_0 + param_1
    # src[_dtw_helion.py:126]: def _dtw_dp_kernel(cost: Tensor, soft: hl.constexpr, diag: hl.constexpr) -> Tensor:
    # src[_dtw_helion.py:127]:     """D of cost (B, R, L), with steps up, left and, if ``diag``, up-left."""
    # src[_dtw_helion.py:128]:     B, R, L = cost.shape
    # src[_dtw_helion.py:126-159]: ...
    return v_0

@triton.jit
def _compose_softmin_plus_whole_1(param_0, param_1, param_2, param_3):
    # src[_dtw_helion.py:141]: prev = hl.associative_scan(_compose_softmin_plus_whole, (c + prev, c), dim=1)[0]
    v_0 = param_3 + param_0
    v_1 = triton_helpers.minimum(param_2, v_0)
    v_2 = param_2 - v_0
    v_3 = tl_math.abs(v_2)
    v_4 = -v_3
    v_5 = libdevice.exp(v_4)
    v_6 = tl.full([], 1.0, tl.float32)
    v_7 = v_5 + v_6
    v_8 = tl_math.log(v_7)
    v_9 = v_1 - v_8
    v_10 = param_3 + param_1
    # src[_dtw_helion.py:126]: def _dtw_dp_kernel(cost: Tensor, soft: hl.constexpr, diag: hl.constexpr) -> Tensor:
    # src[_dtw_helion.py:127]:     """D of cost (B, R, L), with steps up, left and, if ``diag``, up-left."""
    # src[_dtw_helion.py:128]:     B, R, L = cost.shape
    # src[_dtw_helion.py:126-159]: ...
    return (v_9, v_10)

@triton.jit
def _helion__dtw_dp_kernel_c2(cost, D, D_stride_0, D_stride_1, D_stride_2, cost_stride_0, cost_stride_1, cost_stride_2, B, L, R, _NUM_SM: tl.constexpr, _RDIM_SIZE_1: tl.constexpr):
    # src[_dtw_helion.py:130]: for tile_b in hl.tile(B, block_size=1):
    # src[_dtw_helion.py:131]:     prev = hl.cumsum(cost[tile_b, 0, :], dim=1)
    # src[_dtw_helion.py:132]:     D[tile_b, 0, :] = prev
    # src[_dtw_helion.py:130-158]: ...
    total_pids = B
    block_size = tl.cdiv(total_pids, _NUM_SM)
    start_pid = tl.program_id(0) * block_size
    end_pid = start_pid + block_size
    if end_pid > total_pids:
        end_pid = total_pids
    for virtual_pid in tl.range(start_pid, end_pid):
        # src[_dtw_helion.py:130]: for tile_b in hl.tile(B, block_size=1):
        pid_0 = virtual_pid
        offset_0 = pid_0
        indices_0 = offset_0 + tl.zeros([1], tl.int32)
        indices_1 = tl.arange(0, _RDIM_SIZE_1).to(tl.int32)
        mask_1 = indices_1 < L
        # src[_dtw_helion.py:131]: prev = hl.cumsum(cost[tile_b, 0, :], dim=1)
        load = tl.load(cost + (indices_0[:, None] * cost_stride_0 + 0 * cost_stride_1 + (0 + indices_1)[None, :] * cost_stride_2), mask_1[None, :], other=0, eviction_policy='evict_last')
        prev = tl.associative_scan(load, 1, add_0)
        # src[_dtw_helion.py:132]: D[tile_b, 0, :] = prev
        tl.store(D + (indices_0[:, None] * D_stride_0 + 0 * D_stride_1 + (0 + indices_1)[None, :] * D_stride_2), prev, mask_1[None, :])
        # src[_dtw_helion.py:133]: for n in hl.grid(1, R):
        # src[_dtw_helion.py:134]:     c = cost[tile_b, n, :]
        # src[_dtw_helion.py:135]:     identity_a = torch.full_like(c, float("inf"))
        # src[_dtw_helion.py:133-158]: ...
        for offset_2 in tl.range(1, tl.cast(R, tl.int32), flatten=False):
            prev_copy = prev
            prev_copy_0 = prev_copy
            # src[_dtw_helion.py:134]: c = cost[tile_b, n, :]
            c = tl.load(cost + (indices_0[:, None] * cost_stride_0 + offset_2 * cost_stride_1 + (0 + indices_1)[None, :] * cost_stride_2), mask_1[None, :], other=0)
            # src[_dtw_helion.py:141]: prev = hl.associative_scan(_compose_softmin_plus_whole, (c + prev, c), dim=1)[0]
            v_0 = c + prev_copy_0
            prev = tl.associative_scan((v_0, c), 1, _compose_softmin_plus_whole_1)[0]
            # src[_dtw_helion.py:158]: D[tile_b, n, :] = prev
            tl.store(D + (indices_0[:, None] * D_stride_0 + offset_2 * D_stride_1 + (0 + indices_1)[None, :] * D_stride_2), prev, mask_1[None, :])

def __dtw_dp_kernel_c2(cost: Tensor, soft: hl.constexpr, diag: hl.constexpr, *, _launcher=_default_launcher):
    """D of cost (B, R, L), with steps up, left and, if ``diag``, up-left."""
    # src[_dtw_helion.py:128]: B, R, L = cost.shape
    B, R, L = cost.shape
    # src[_dtw_helion.py:129]: D = torch.empty_like(cost)
    D = torch.empty_like(cost)
    # src[_dtw_helion.py:130]: for tile_b in hl.tile(B, block_size=1):
    _NUM_SM = _get_num_sm(cost.device)
    _RDIM_SIZE_1 = triton.next_power_of_2(L)
    # src[_dtw_helion.py:130]: for tile_b in hl.tile(B, block_size=1):
    # src[_dtw_helion.py:131]:     prev = hl.cumsum(cost[tile_b, 0, :], dim=1)
    # src[_dtw_helion.py:132]:     D[tile_b, 0, :] = prev
    # src[_dtw_helion.py:130-158]: ...
    _launcher(_helion__dtw_dp_kernel_c2, (_NUM_SM,), cost, D, D.stride(0), D.stride(1), D.stride(2), cost.stride(0), cost.stride(1), cost.stride(2), B, L, R, _NUM_SM, _RDIM_SIZE_1, num_warps=16, num_stages=1)
    # src[_dtw_helion.py:159]: return D
    return D

# =================================================================
# Config 3
# =================================================================

@triton.jit
def add_0(param_0, param_1):
    # src[_dtw_helion.py:131]: prev = hl.cumsum(cost[tile_b, 0, :], dim=1)
    v_0 = param_0 + param_1
    # src[_dtw_helion.py:126]: def _dtw_dp_kernel(cost: Tensor, soft: hl.constexpr, diag: hl.constexpr) -> Tensor:
    # src[_dtw_helion.py:127]:     """D of cost (B, R, L), with steps up, left and, if ``diag``, up-left."""
    # src[_dtw_helion.py:128]:     B, R, L = cost.shape
    # src[_dtw_helion.py:126-159]: ...
    return v_0

@triton.jit
def _compose_softmin_plus_whole_1(param_0, param_1, param_2, param_3):
    # src[_dtw_helion.py:141]: prev = hl.associative_scan(_compose_softmin_plus_whole, (c + prev, c), dim=1)[0]
    v_0 = param_3 + param_0
    v_1 = triton_helpers.minimum(param_2, v_0)
    v_2 = param_2 - v_0
    v_3 = tl_math.abs(v_2)
    v_4 = -v_3
    v_5 = libdevice.exp(v_4)
    v_6 = tl.full([], 1.0, tl.float32)
    v_7 = v_5 + v_6
    v_8 = tl_math.log(v_7)
    v_9 = v_1 - v_8
    v_10 = param_3 + param_1
    # src[_dtw_helion.py:126]: def _dtw_dp_kernel(cost: Tensor, soft: hl.constexpr, diag: hl.constexpr) -> Tensor:
    # src[_dtw_helion.py:127]:     """D of cost (B, R, L), with steps up, left and, if ``diag``, up-left."""
    # src[_dtw_helion.py:128]:     B, R, L = cost.shape
    # src[_dtw_helion.py:126-159]: ...
    return (v_9, v_10)

@triton.jit
def _helion__dtw_dp_kernel_c3(cost, D, D_stride_0, D_stride_1, D_stride_2, cost_stride_0, cost_stride_1, cost_stride_2, L, R, _RDIM_SIZE_1: tl.constexpr):
    # src[_dtw_helion.py:130]: for tile_b in hl.tile(B, block_size=1):
    pid_0 = tl.program_id(0)
    offset_0 = pid_0
    indices_0 = offset_0 + tl.zeros([1], tl.int32)
    indices_1 = tl.arange(0, _RDIM_SIZE_1).to(tl.int32)
    mask_1 = indices_1 < L
    # src[_dtw_helion.py:131]: prev = hl.cumsum(cost[tile_b, 0, :], dim=1)
    load = tl.load(cost + (indices_0[:, None] * cost_stride_0 + 0 * cost_stride_1 + (0 + indices_1)[None, :] * cost_stride_2), mask_1[None, :], other=0, eviction_policy='evict_last')
    prev = tl.associative_scan(load, 1, add_0)
    # src[_dtw_helion.py:132]: D[tile_b, 0, :] = prev
    tl.store(D + (indices_0[:, None] * D_stride_0 + 0 * D_stride_1 + (0 + indices_1)[None, :] * D_stride_2), prev, mask_1[None, :])
    # src[_dtw_helion.py:133]: for n in hl.grid(1, R):
    # src[_dtw_helion.py:134]:     c = cost[tile_b, n, :]
    # src[_dtw_helion.py:135]:     identity_a = torch.full_like(c, float("inf"))
    # src[_dtw_helion.py:133-158]: ...
    for offset_2 in tl.range(1, tl.cast(R, tl.int32)):
        prev_copy = prev
        prev_copy_0 = prev_copy
        # src[_dtw_helion.py:134]: c = cost[tile_b, n, :]
        c = tl.load(cost + (indices_0[:, None] * cost_stride_0 + offset_2 * cost_stride_1 + (0 + indices_1)[None, :] * cost_stride_2), mask_1[None, :], other=0, eviction_policy='evict_last')
        # src[_dtw_helion.py:141]: prev = hl.associative_scan(_compose_softmin_plus_whole, (c + prev, c), dim=1)[0]
        v_0 = c + prev_copy_0
        prev = tl.associative_scan((v_0, c), 1, _compose_softmin_plus_whole_1)[0]
        # src[_dtw_helion.py:158]: D[tile_b, n, :] = prev
        tl.store(D + (indices_0[:, None] * D_stride_0 + offset_2 * D_stride_1 + (0 + indices_1)[None, :] * D_stride_2), prev, mask_1[None, :])

def __dtw_dp_kernel_c3(cost: Tensor, soft: hl.constexpr, diag: hl.constexpr, *, _launcher=_default_launcher):
    """D of cost (B, R, L), with steps up, left and, if ``diag``, up-left."""
    # src[_dtw_helion.py:128]: B, R, L = cost.shape
    B, R, L = cost.shape
    # src[_dtw_helion.py:129]: D = torch.empty_like(cost)
    D = torch.empty_like(cost)
    # src[_dtw_helion.py:130]: for tile_b in hl.tile(B, block_size=1):
    _RDIM_SIZE_1 = triton.next_power_of_2(L)
    # src[_dtw_helion.py:130]: for tile_b in hl.tile(B, block_size=1):
    # src[_dtw_helion.py:131]:     prev = hl.cumsum(cost[tile_b, 0, :], dim=1)
    # src[_dtw_helion.py:132]:     D[tile_b, 0, :] = prev
    # src[_dtw_helion.py:130-158]: ...
    _launcher(_helion__dtw_dp_kernel_c3, (B,), cost, D, D.stride(0), D.stride(1), D.stride(2), cost.stride(0), cost.stride(1), cost.stride(2), L, R, _RDIM_SIZE_1, num_warps=8, num_stages=5)
    # src[_dtw_helion.py:159]: return D
    return D

# =================================================================
# Heuristic dispatch
# =================================================================

def key__dtw_dp_kernel(*args) -> int:
    _arg0_dim2 = int(args[0].shape[2]) if len(args) > 0 and isinstance(args[0], torch.Tensor) and args[0].ndim > 2 else 0
    _arg1_scalar = args[1] if len(args) > 1 and isinstance(args[1], (int, float)) else 0
    _arg2_scalar = args[2] if len(args) > 2 and isinstance(args[2], (int, float)) else 0
    if _arg0_dim2 <= 1024.0:
        if _arg1_scalar <= 0.0:
            if _arg0_dim2 <= 128.0:
                return 0
            else:
                if _arg2_scalar <= 0.0:
                    if _arg0_dim2 <= 256.0:
                        return 3
                    else:
                        return 0
                else:
                    return 3
        else:
            if _arg0_dim2 <= 512.0:
                if _arg0_dim2 <= 128.0:
                    return 1
                else:
                    return 1
            else:
                return 1
    else:
        if _arg0_dim2 <= 4096.0:
            if _arg0_dim2 <= 2048.0:
                return 0
            else:
                if _arg1_scalar <= 0.0:
                    return 0
                else:
                    if _arg2_scalar <= 0.0:
                        return 0
                    else:
                        return 2
        else:
            if _arg1_scalar <= 0.0:
                return 1
            else:
                return 2


# === Kernel: _dag_forward_kernel ===



def _dtw_dp_kernel(*args, **kwargs):
    return [
        __dtw_dp_kernel_c0,
        __dtw_dp_kernel_c1,
        __dtw_dp_kernel_c2,
        __dtw_dp_kernel_c3,
    ][key__dtw_dp_kernel(*args)](*args, **kwargs)
