# Generated by scripts/helion_aot.py; do not edit.
# ruff: noqa
# fmt: off
# Auto-generated standalone Triton kernel for '_log_bmm_kernel'.
# No Helion dependency required at runtime.

from __future__ import annotations

from torch._inductor.runtime import triton_helpers
from torch._inductor.runtime.triton_compat import libdevice
from torch._inductor.runtime.triton_helpers import math as tl_math
import torch
import triton
import triton.language as tl


def _default_launcher(
    triton_kernel,
    grid,
    *args,
    num_warps,
    num_stages,
    launch_cooperative_grid=False,
    **kwargs,
):
    return triton_kernel.run(
        *args,
        grid=grid,
        warmup=False,
        num_warps=num_warps,
        num_stages=num_stages,
        launch_cooperative_grid=launch_cooperative_grid,
        **kwargs,
    )


# =================================================================
# Config 0
# =================================================================

_BLOCK_SIZE_0_c0 = tl.constexpr(16)
_BLOCK_SIZE_1_c0 = tl.constexpr(4)
_BLOCK_SIZE_2_c0 = tl.constexpr(4)
_BLOCK_SIZE_3_c0 = tl.constexpr(4)

@triton.jit
def _helion__log_bmm_kernel_c0(a, b, out, a_stride_0, a_stride_1, a_stride_2, b_stride_0, b_stride_1, b_stride_2, out_stride_0, out_stride_1, out_stride_2, n_p, n_i, n_k, n_j):
    # src[_semiring_helion.py:70]: for tile_p, tile_i, tile_k in hl.tile([n_p, n_i, n_k]):
    num_blocks_0 = tl.cdiv(n_p, _BLOCK_SIZE_0_c0)
    num_blocks_1 = tl.cdiv(n_i, _BLOCK_SIZE_1_c0)
    pid_0 = tl.program_id(0) % num_blocks_0
    pid_1 = tl.program_id(0) // num_blocks_0 % num_blocks_1
    pid_2 = tl.program_id(0) // (num_blocks_0 * num_blocks_1)
    offset_0 = pid_0 * _BLOCK_SIZE_0_c0
    indices_0 = (offset_0 + tl.arange(0, _BLOCK_SIZE_0_c0)).to(tl.int32)
    mask_0 = indices_0 < n_p
    offset_1 = pid_1 * _BLOCK_SIZE_1_c0
    indices_1 = (offset_1 + tl.arange(0, _BLOCK_SIZE_1_c0)).to(tl.int32)
    mask_1 = indices_1 < n_i
    offset_2 = pid_2 * _BLOCK_SIZE_2_c0
    indices_2 = (offset_2 + tl.arange(0, _BLOCK_SIZE_2_c0)).to(tl.int32)
    mask_2 = indices_2 < n_k
    # src[_semiring_helion.py:71]: running_max = hl.full([tile_p, tile_i, tile_k], float("-inf"), dtype=a.dtype)
    running_max = tl.full([_BLOCK_SIZE_0_c0, _BLOCK_SIZE_1_c0, _BLOCK_SIZE_2_c0], float('-inf'), tl.float32)
    # src[_semiring_helion.py:72]: running_sum = hl.zeros([tile_p, tile_i, tile_k], dtype=a.dtype)
    running_sum = tl.full([_BLOCK_SIZE_0_c0, _BLOCK_SIZE_1_c0, _BLOCK_SIZE_2_c0], 0.0, tl.float32)
    # src[_semiring_helion.py:73]: for tile_j in hl.tile(n_j):
    # src[_semiring_helion.py:74]:     terms = (
    # src[_semiring_helion.py:75]:         a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
    # src[_semiring_helion.py:73-83]: ...
    for offset_3 in tl.range(0, tl.cast(n_j, tl.int32), _BLOCK_SIZE_3_c0):
        indices_3 = offset_3 + tl.arange(0, _BLOCK_SIZE_3_c0).to(tl.int32)
        mask_3 = indices_3 < n_j
        running_max_copy = running_max
        running_sum_copy = running_sum
        running_max_copy_0 = running_max_copy
        running_sum_copy_0 = running_sum_copy
        # src[_semiring_helion.py:75]: a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
        load = tl.load(a + (indices_0[:, None, None] * a_stride_0 + indices_1[None, :, None] * a_stride_1 + indices_3[None, None, :] * a_stride_2), mask_0[:, None, None] & mask_1[None, :, None] & mask_3[None, None, :], other=0)
        subscript = load[:, :, :, None]
        load_1 = tl.load(b + (indices_0[:, None, None] * b_stride_0 + indices_3[None, :, None] * b_stride_1 + indices_2[None, None, :] * b_stride_2), mask_0[:, None, None] & mask_3[None, :, None] & mask_2[None, None, :], other=0)
        subscript_1 = load_1[:, None, :, :]
        v_0 = subscript + subscript_1
        # src[_semiring_helion.py:77]: new_max = torch.maximum(running_max, torch.amax(terms, dim=2))
        _mask_to = tl.where(mask_0[:, None, None, None] & mask_1[None, :, None, None] & mask_3[None, None, :, None] & mask_2[None, None, None, :], v_0, tl.full([], float('-inf'), tl.float32))
        amax = tl.cast(tl.max(_mask_to, 2), tl.float32)
        v_1 = triton_helpers.maximum(running_max_copy_0, amax)
        # src[_semiring_helion.py:79]: shift = torch.where(new_max == float("-inf"), torch.zeros_like(new_max), new_max)
        v_2 = tl.full([], float('-inf'), tl.float32)
        v_3 = v_1 == v_2
        full = tl.full([_BLOCK_SIZE_0_c0, _BLOCK_SIZE_1_c0, _BLOCK_SIZE_2_c0], 0, tl.float32)
        shift = tl.where(v_3, full, v_1)
        # src[_semiring_helion.py:80]: running_sum = running_sum * torch.exp(running_max - shift) + torch.sum(
        v_4 = running_max_copy_0 - shift
        v_5 = libdevice.exp(v_4)
        v_6 = running_sum_copy_0 * v_5
        # src[_semiring_helion.py:81]: torch.exp(terms - shift[:, :, None, :]), dim=2
        subscript_2 = shift[:, :, None, :]
        v_7 = v_0 - subscript_2
        v_8 = libdevice.exp(v_7)
        # src[_semiring_helion.py:80]: running_sum = running_sum * torch.exp(running_max - shift) + torch.sum(
        # src[_semiring_helion.py:81]:     torch.exp(terms - shift[:, :, None, :]), dim=2
        # src[_semiring_helion.py:82]: )
        _mask_to_1 = tl.where(mask_0[:, None, None, None] & mask_1[None, :, None, None] & mask_3[None, None, :, None] & mask_2[None, None, None, :], v_8, tl.full([], 0, tl.float32))
        sum_1 = tl.cast(tl.sum(_mask_to_1, 2), tl.float32)
        running_sum = v_6 + sum_1
        # src[_semiring_helion.py:83]: running_max = new_max
        running_max = v_1
    # src[_semiring_helion.py:84]: out[tile_p, tile_i, tile_k] = running_max + torch.log(running_sum)
    v_10 = tl_math.log(running_sum)
    v_11 = running_max + v_10
    tl.store(out + (indices_0[:, None, None] * out_stride_0 + indices_1[None, :, None] * out_stride_1 + indices_2[None, None, :] * out_stride_2), v_11, mask_0[:, None, None] & mask_1[None, :, None] & mask_2[None, None, :])

def __log_bmm_kernel_c0(a: Tensor, b: Tensor, *, _launcher=_default_launcher):
    # src[_semiring_helion.py:67]: n_p, n_i, n_j = a.shape
    n_p, n_i, n_j = a.shape
    # src[_semiring_helion.py:68]: n_k = b.size(-1)
    n_k = b.size(-1)
    # src[_semiring_helion.py:69]: out = torch.empty([n_p, n_i, n_k], dtype=a.dtype, device=a.device)
    out = torch.empty([n_p, n_i, n_k], dtype=a.dtype, device=a.device)
    # src[_semiring_helion.py:70]: for tile_p, tile_i, tile_k in hl.tile([n_p, n_i, n_k]):
    _BLOCK_SIZE_0_c0 = 16
    _BLOCK_SIZE_1_c0 = 4
    _BLOCK_SIZE_2_c0 = 4
    # src[_semiring_helion.py:70]: for tile_p, tile_i, tile_k in hl.tile([n_p, n_i, n_k]):
    # src[_semiring_helion.py:71]:     running_max = hl.full([tile_p, tile_i, tile_k], float("-inf"), dtype=a.dtype)
    # src[_semiring_helion.py:72]:     running_sum = hl.zeros([tile_p, tile_i, tile_k], dtype=a.dtype)
    # src[_semiring_helion.py:70-84]: ...
    _launcher(_helion__log_bmm_kernel_c0, ((n_p + _BLOCK_SIZE_0_c0 - 1) // _BLOCK_SIZE_0_c0 * ((n_i + _BLOCK_SIZE_1_c0 - 1) // _BLOCK_SIZE_1_c0) * ((n_k + _BLOCK_SIZE_2_c0 - 1) // _BLOCK_SIZE_2_c0),), a, b, out, a.stride(0), a.stride(1), a.stride(2), b.stride(0), b.stride(1), b.stride(2), out.stride(0), out.stride(1), out.stride(2), n_p, n_i, n_k, n_j, num_warps=4, num_stages=1)
    # src[_semiring_helion.py:85]: return out
    return out

# =================================================================
# Config 1
# =================================================================

_BLOCK_SIZE_2_c1 = tl.constexpr(4)
_BLOCK_SIZE_1_c1 = tl.constexpr(16)
_BLOCK_SIZE_0_c1 = tl.constexpr(8)
_BLOCK_SIZE_3_c1 = tl.constexpr(2)

@triton.jit
def _helion__log_bmm_kernel_c1(a, b, out, a_stride_0, a_stride_1, a_stride_2, b_stride_0, b_stride_1, b_stride_2, out_stride_0, out_stride_1, out_stride_2, n_k, n_i, n_p, n_j):
    # src[_semiring_helion.py:70]: for tile_p, tile_i, tile_k in hl.tile([n_p, n_i, n_k]):
    num_blocks_0 = tl.cdiv(n_k, _BLOCK_SIZE_2_c1)
    num_blocks_1 = tl.cdiv(n_i, _BLOCK_SIZE_1_c1)
    pid_0 = tl.program_id(0) % num_blocks_0
    pid_1 = tl.program_id(0) // num_blocks_0 % num_blocks_1
    pid_2 = tl.program_id(0) // (num_blocks_0 * num_blocks_1)
    offset_2 = pid_0 * _BLOCK_SIZE_2_c1
    indices_2 = (offset_2 + tl.arange(0, _BLOCK_SIZE_2_c1)).to(tl.int32)
    mask_2 = indices_2 < n_k
    offset_1 = pid_1 * _BLOCK_SIZE_1_c1
    indices_1 = (offset_1 + tl.arange(0, _BLOCK_SIZE_1_c1)).to(tl.int32)
    mask_1 = indices_1 < n_i
    offset_0 = pid_2 * _BLOCK_SIZE_0_c1
    indices_0 = (offset_0 + tl.arange(0, _BLOCK_SIZE_0_c1)).to(tl.int32)
    mask_0 = indices_0 < n_p
    # src[_semiring_helion.py:71]: running_max = hl.full([tile_p, tile_i, tile_k], float("-inf"), dtype=a.dtype)
    running_max = tl.full([_BLOCK_SIZE_0_c1, _BLOCK_SIZE_1_c1, _BLOCK_SIZE_2_c1], float('-inf'), tl.float32)
    # src[_semiring_helion.py:72]: running_sum = hl.zeros([tile_p, tile_i, tile_k], dtype=a.dtype)
    running_sum = tl.full([_BLOCK_SIZE_0_c1, _BLOCK_SIZE_1_c1, _BLOCK_SIZE_2_c1], 0.0, tl.float32)
    # src[_semiring_helion.py:73]: for tile_j in hl.tile(n_j):
    # src[_semiring_helion.py:74]:     terms = (
    # src[_semiring_helion.py:75]:         a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
    # src[_semiring_helion.py:73-83]: ...
    for offset_3 in tl.range(0, tl.cast(n_j, tl.int32), _BLOCK_SIZE_3_c1, disallow_acc_multi_buffer=True):
        indices_3 = offset_3 + tl.arange(0, _BLOCK_SIZE_3_c1).to(tl.int32)
        mask_3 = indices_3 < n_j
        running_max_copy = running_max
        running_sum_copy = running_sum
        running_max_copy_0 = running_max_copy
        running_sum_copy_0 = running_sum_copy
        # src[_semiring_helion.py:75]: a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
        load = tl.load(a + (indices_0[:, None, None] * a_stride_0 + indices_1[None, :, None] * a_stride_1 + indices_3[None, None, :] * a_stride_2), mask_0[:, None, None] & mask_1[None, :, None] & mask_3[None, None, :], other=0)
        subscript = load[:, :, :, None]
        load_1 = tl.load(b + (indices_0[:, None, None] * b_stride_0 + indices_3[None, :, None] * b_stride_1 + indices_2[None, None, :] * b_stride_2), mask_0[:, None, None] & mask_3[None, :, None] & mask_2[None, None, :], other=0)
        subscript_1 = load_1[:, None, :, :]
        v_0 = subscript + subscript_1
        # src[_semiring_helion.py:77]: new_max = torch.maximum(running_max, torch.amax(terms, dim=2))
        _mask_to = tl.where(mask_0[:, None, None, None] & mask_1[None, :, None, None] & mask_3[None, None, :, None] & mask_2[None, None, None, :], v_0, tl.full([], float('-inf'), tl.float32))
        amax = tl.cast(tl.max(_mask_to, 2), tl.float32)
        v_1 = triton_helpers.maximum(running_max_copy_0, amax)
        # src[_semiring_helion.py:79]: shift = torch.where(new_max == float("-inf"), torch.zeros_like(new_max), new_max)
        v_2 = tl.full([], float('-inf'), tl.float32)
        v_3 = v_1 == v_2
        full = tl.full([_BLOCK_SIZE_0_c1, _BLOCK_SIZE_1_c1, _BLOCK_SIZE_2_c1], 0, tl.float32)
        shift = tl.where(v_3, full, v_1)
        # src[_semiring_helion.py:80]: running_sum = running_sum * torch.exp(running_max - shift) + torch.sum(
        v_4 = running_max_copy_0 - shift
        v_5 = libdevice.exp(v_4)
        v_6 = running_sum_copy_0 * v_5
        # src[_semiring_helion.py:81]: torch.exp(terms - shift[:, :, None, :]), dim=2
        subscript_2 = shift[:, :, None, :]
        v_7 = v_0 - subscript_2
        v_8 = libdevice.exp(v_7)
        # src[_semiring_helion.py:80]: running_sum = running_sum * torch.exp(running_max - shift) + torch.sum(
        # src[_semiring_helion.py:81]:     torch.exp(terms - shift[:, :, None, :]), dim=2
        # src[_semiring_helion.py:82]: )
        _mask_to_1 = tl.where(mask_0[:, None, None, None] & mask_1[None, :, None, None] & mask_3[None, None, :, None] & mask_2[None, None, None, :], v_8, tl.full([], 0, tl.float32))
        sum_1 = tl.cast(tl.sum(_mask_to_1, 2), tl.float32)
        running_sum = v_6 + sum_1
        # src[_semiring_helion.py:83]: running_max = new_max
        running_max = v_1
    # src[_semiring_helion.py:84]: out[tile_p, tile_i, tile_k] = running_max + torch.log(running_sum)
    v_10 = tl_math.log(running_sum)
    v_11 = running_max + v_10
    tl.store(out + (indices_0[:, None, None] * out_stride_0 + indices_1[None, :, None] * out_stride_1 + indices_2[None, None, :] * out_stride_2), v_11, mask_0[:, None, None] & mask_1[None, :, None] & mask_2[None, None, :])

def __log_bmm_kernel_c1(a: Tensor, b: Tensor, *, _launcher=_default_launcher):
    # src[_semiring_helion.py:67]: n_p, n_i, n_j = a.shape
    n_p, n_i, n_j = a.shape
    # src[_semiring_helion.py:68]: n_k = b.size(-1)
    n_k = b.size(-1)
    # src[_semiring_helion.py:69]: out = torch.empty([n_p, n_i, n_k], dtype=a.dtype, device=a.device)
    out = torch.empty([n_p, n_i, n_k], dtype=a.dtype, device=a.device)
    # src[_semiring_helion.py:70]: for tile_p, tile_i, tile_k in hl.tile([n_p, n_i, n_k]):
    _BLOCK_SIZE_2_c1 = 4
    _BLOCK_SIZE_1_c1 = 16
    _BLOCK_SIZE_0_c1 = 8
    # src[_semiring_helion.py:70]: for tile_p, tile_i, tile_k in hl.tile([n_p, n_i, n_k]):
    # src[_semiring_helion.py:71]:     running_max = hl.full([tile_p, tile_i, tile_k], float("-inf"), dtype=a.dtype)
    # src[_semiring_helion.py:72]:     running_sum = hl.zeros([tile_p, tile_i, tile_k], dtype=a.dtype)
    # src[_semiring_helion.py:70-84]: ...
    _launcher(_helion__log_bmm_kernel_c1, ((n_k + _BLOCK_SIZE_2_c1 - 1) // _BLOCK_SIZE_2_c1 * ((n_i + _BLOCK_SIZE_1_c1 - 1) // _BLOCK_SIZE_1_c1) * ((n_p + _BLOCK_SIZE_0_c1 - 1) // _BLOCK_SIZE_0_c1),), a, b, out, a.stride(0), a.stride(1), a.stride(2), b.stride(0), b.stride(1), b.stride(2), out.stride(0), out.stride(1), out.stride(2), n_k, n_i, n_p, n_j, num_warps=2, num_stages=1)
    # src[_semiring_helion.py:85]: return out
    return out

# =================================================================
# Heuristic dispatch
# =================================================================

def key__log_bmm_kernel(*args) -> int:
    _arg0_dim1 = int(args[0].shape[1]) if len(args) > 0 and isinstance(args[0], torch.Tensor) and args[0].ndim > 1 else 0
    if _arg0_dim1 <= 32.0:
        return 0
    else:
        return 1


# === Kernel: _max_bmm_kernel ===


# === Kernel: _contract_over_i ===


# === Kernel: _contract_over_j ===


# === Kernel: _contract_over_k ===



def _log_bmm_kernel(*args, **kwargs):
    return [
        __log_bmm_kernel_c0,
        __log_bmm_kernel_c1,
    ][key__log_bmm_kernel(*args)](*args, **kwargs)
