# Generated by scripts/helion_aot.py; do not edit.
# ruff: noqa
# fmt: off
# Auto-generated standalone Triton kernel for '_max_bmm_kernel'.
# No Helion dependency required at runtime.

from __future__ import annotations

from torch._inductor.runtime import triton_helpers
import torch
import triton
import triton.language as tl


def _default_launcher(
    triton_kernel,
    grid,
    *args,
    num_warps,
    num_stages,
    launch_cooperative_grid=False,
    **kwargs,
):
    return triton_kernel.run(
        *args,
        grid=grid,
        warmup=False,
        num_warps=num_warps,
        num_stages=num_stages,
        launch_cooperative_grid=launch_cooperative_grid,
        **kwargs,
    )


# =================================================================
# Config 0
# =================================================================

_BLOCK_SIZE_0_c0 = tl.constexpr(16)
_BLOCK_SIZE_1_c0 = tl.constexpr(4)
_BLOCK_SIZE_2_c0 = tl.constexpr(4)
_BLOCK_SIZE_3_c0 = tl.constexpr(4)

@triton.jit
def _helion__max_bmm_kernel_c0(a, b, out, a_stride_0, a_stride_1, a_stride_2, b_stride_0, b_stride_1, b_stride_2, out_stride_0, out_stride_1, out_stride_2, n_p, n_i, n_k, n_j):
    # src[_semiring_helion.py:93]: for tile_p, tile_i, tile_k in hl.tile([n_p, n_i, n_k]):
    num_blocks_0 = tl.cdiv(n_p, _BLOCK_SIZE_0_c0)
    num_blocks_1 = tl.cdiv(n_i, _BLOCK_SIZE_1_c0)
    pid_0 = tl.program_id(0) % num_blocks_0
    pid_1 = tl.program_id(0) // num_blocks_0 % num_blocks_1
    pid_2 = tl.program_id(0) // (num_blocks_0 * num_blocks_1)
    offset_0 = pid_0 * _BLOCK_SIZE_0_c0
    indices_0 = (offset_0 + tl.arange(0, _BLOCK_SIZE_0_c0)).to(tl.int32)
    mask_0 = indices_0 < n_p
    offset_1 = pid_1 * _BLOCK_SIZE_1_c0
    indices_1 = (offset_1 + tl.arange(0, _BLOCK_SIZE_1_c0)).to(tl.int32)
    mask_1 = indices_1 < n_i
    offset_2 = pid_2 * _BLOCK_SIZE_2_c0
    indices_2 = (offset_2 + tl.arange(0, _BLOCK_SIZE_2_c0)).to(tl.int32)
    mask_2 = indices_2 < n_k
    # src[_semiring_helion.py:94]: running_max = hl.full([tile_p, tile_i, tile_k], float("-inf"), dtype=a.dtype)
    running_max = tl.full([_BLOCK_SIZE_0_c0, _BLOCK_SIZE_1_c0, _BLOCK_SIZE_2_c0], float('-inf'), tl.float32)
    # src[_semiring_helion.py:95]: for tile_j in hl.tile(n_j):
    # src[_semiring_helion.py:96]:     terms = (
    # src[_semiring_helion.py:97]:         a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
    # src[_semiring_helion.py:95-99]: ...
    for offset_3 in tl.range(0, tl.cast(n_j, tl.int32), _BLOCK_SIZE_3_c0):
        indices_3 = offset_3 + tl.arange(0, _BLOCK_SIZE_3_c0).to(tl.int32)
        mask_3 = indices_3 < n_j
        running_max_copy = running_max
        running_max_copy_0 = running_max_copy
        # src[_semiring_helion.py:97]: a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
        load = tl.load(a + (indices_0[:, None, None] * a_stride_0 + indices_1[None, :, None] * a_stride_1 + indices_3[None, None, :] * a_stride_2), mask_0[:, None, None] & mask_1[None, :, None] & mask_3[None, None, :], other=0)
        subscript = load[:, :, :, None]
        load_1 = tl.load(b + (indices_0[:, None, None] * b_stride_0 + indices_3[None, :, None] * b_stride_1 + indices_2[None, None, :] * b_stride_2), mask_0[:, None, None] & mask_3[None, :, None] & mask_2[None, None, :], other=0)
        subscript_1 = load_1[:, None, :, :]
        v_0 = subscript + subscript_1
        # src[_semiring_helion.py:99]: running_max = torch.maximum(running_max, torch.amax(terms, dim=2))
        _mask_to = tl.where(mask_0[:, None, None, None] & mask_1[None, :, None, None] & mask_3[None, None, :, None] & mask_2[None, None, None, :], v_0, tl.full([], float('-inf'), tl.float32))
        amax = tl.cast(tl.max(_mask_to, 2), tl.float32)
        running_max = triton_helpers.maximum(running_max_copy_0, amax)
    # src[_semiring_helion.py:100]: out[tile_p, tile_i, tile_k] = running_max
    tl.store(out + (indices_0[:, None, None] * out_stride_0 + indices_1[None, :, None] * out_stride_1 + indices_2[None, None, :] * out_stride_2), running_max, mask_0[:, None, None] & mask_1[None, :, None] & mask_2[None, None, :])

def __max_bmm_kernel_c0(a: Tensor, b: Tensor, *, _launcher=_default_launcher):
    # src[_semiring_helion.py:90]: n_p, n_i, n_j = a.shape
    n_p, n_i, n_j = a.shape
    # src[_semiring_helion.py:91]: n_k = b.size(-1)
    n_k = b.size(-1)
    # src[_semiring_helion.py:92]: out = torch.empty([n_p, n_i, n_k], dtype=a.dtype, device=a.device)
    out = torch.empty([n_p, n_i, n_k], dtype=a.dtype, device=a.device)
    # src[_semiring_helion.py:93]: for tile_p, tile_i, tile_k in hl.tile([n_p, n_i, n_k]):
    _BLOCK_SIZE_0_c0 = 16
    _BLOCK_SIZE_1_c0 = 4
    _BLOCK_SIZE_2_c0 = 4
    # src[_semiring_helion.py:93]: for tile_p, tile_i, tile_k in hl.tile([n_p, n_i, n_k]):
    # src[_semiring_helion.py:94]:     running_max = hl.full([tile_p, tile_i, tile_k], float("-inf"), dtype=a.dtype)
    # src[_semiring_helion.py:95]:     for tile_j in hl.tile(n_j):
    # src[_semiring_helion.py:93-100]: ...
    _launcher(_helion__max_bmm_kernel_c0, ((n_p + _BLOCK_SIZE_0_c0 - 1) // _BLOCK_SIZE_0_c0 * ((n_i + _BLOCK_SIZE_1_c0 - 1) // _BLOCK_SIZE_1_c0) * ((n_k + _BLOCK_SIZE_2_c0 - 1) // _BLOCK_SIZE_2_c0),), a, b, out, a.stride(0), a.stride(1), a.stride(2), b.stride(0), b.stride(1), b.stride(2), out.stride(0), out.stride(1), out.stride(2), n_p, n_i, n_k, n_j, num_warps=4, num_stages=1)
    # src[_semiring_helion.py:101]: return out
    return out

# =================================================================
# Config 1
# =================================================================

_BLOCK_SIZE_0_c1 = tl.constexpr(4)
_BLOCK_SIZE_1_c1 = tl.constexpr(8)
_BLOCK_SIZE_2_c1 = tl.constexpr(32)
_BLOCK_SIZE_3_c1 = tl.constexpr(4)

@triton.jit
def _helion__max_bmm_kernel_c1(a, b, out, a_stride_0, a_stride_1, a_stride_2, b_stride_0, b_stride_1, b_stride_2, out_stride_0, out_stride_1, out_stride_2, n_p, n_i, n_k, n_j):
    # src[_semiring_helion.py:93]: for tile_p, tile_i, tile_k in hl.tile([n_p, n_i, n_k]):
    num_blocks_0 = tl.cdiv(n_p, _BLOCK_SIZE_0_c1)
    num_blocks_1 = tl.cdiv(n_i, _BLOCK_SIZE_1_c1)
    pid_0 = tl.program_id(0) % num_blocks_0
    pid_1 = tl.program_id(0) // num_blocks_0 % num_blocks_1
    pid_2 = tl.program_id(0) // (num_blocks_0 * num_blocks_1)
    offset_0 = pid_0 * _BLOCK_SIZE_0_c1
    indices_0 = (offset_0 + tl.arange(0, _BLOCK_SIZE_0_c1)).to(tl.int32)
    mask_0 = indices_0 < n_p
    offset_1 = pid_1 * _BLOCK_SIZE_1_c1
    indices_1 = (offset_1 + tl.arange(0, _BLOCK_SIZE_1_c1)).to(tl.int32)
    mask_1 = indices_1 < n_i
    offset_2 = pid_2 * _BLOCK_SIZE_2_c1
    indices_2 = (offset_2 + tl.arange(0, _BLOCK_SIZE_2_c1)).to(tl.int32)
    mask_2 = indices_2 < n_k
    # src[_semiring_helion.py:94]: running_max = hl.full([tile_p, tile_i, tile_k], float("-inf"), dtype=a.dtype)
    running_max = tl.full([_BLOCK_SIZE_0_c1, _BLOCK_SIZE_1_c1, _BLOCK_SIZE_2_c1], float('-inf'), tl.float32)
    # src[_semiring_helion.py:95]: for tile_j in hl.tile(n_j):
    # src[_semiring_helion.py:96]:     terms = (
    # src[_semiring_helion.py:97]:         a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
    # src[_semiring_helion.py:95-99]: ...
    for offset_3 in tl.range(0, tl.cast(n_j, tl.int32), _BLOCK_SIZE_3_c1, loop_unroll_factor=1, disallow_acc_multi_buffer=True):
        indices_3 = offset_3 + tl.arange(0, _BLOCK_SIZE_3_c1).to(tl.int32)
        mask_3 = indices_3 < n_j
        running_max_copy = running_max
        running_max_copy_0 = running_max_copy
        # src[_semiring_helion.py:97]: a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
        load = tl.load(a + (indices_0[:, None, None] * a_stride_0 + indices_1[None, :, None] * a_stride_1 + indices_3[None, None, :] * a_stride_2), mask_0[:, None, None] & mask_1[None, :, None] & mask_3[None, None, :], other=0)
        subscript = load[:, :, :, None]
        load_1 = tl.load(b + (indices_0[:, None, None] * b_stride_0 + indices_3[None, :, None] * b_stride_1 + indices_2[None, None, :] * b_stride_2), mask_0[:, None, None] & mask_3[None, :, None] & mask_2[None, None, :], other=0)
        subscript_1 = load_1[:, None, :, :]
        v_0 = subscript + subscript_1
        # src[_semiring_helion.py:99]: running_max = torch.maximum(running_max, torch.amax(terms, dim=2))
        _mask_to = tl.where(mask_0[:, None, None, None] & mask_1[None, :, None, None] & mask_3[None, None, :, None] & mask_2[None, None, None, :], v_0, tl.full([], float('-inf'), tl.float32))
        amax = tl.cast(tl.max(_mask_to, 2), tl.float32)
        running_max = triton_helpers.maximum(running_max_copy_0, amax)
    # src[_semiring_helion.py:100]: out[tile_p, tile_i, tile_k] = running_max
    tl.store(out + (indices_0[:, None, None] * out_stride_0 + indices_1[None, :, None] * out_stride_1 + indices_2[None, None, :] * out_stride_2), running_max, mask_0[:, None, None] & mask_1[None, :, None] & mask_2[None, None, :])

def __max_bmm_kernel_c1(a: Tensor, b: Tensor, *, _launcher=_default_launcher):
    # src[_semiring_helion.py:90]: n_p, n_i, n_j = a.shape
    n_p, n_i, n_j = a.shape
    # src[_semiring_helion.py:91]: n_k = b.size(-1)
    n_k = b.size(-1)
    # src[_semiring_helion.py:92]: out = torch.empty([n_p, n_i, n_k], dtype=a.dtype, device=a.device)
    out = torch.empty([n_p, n_i, n_k], dtype=a.dtype, device=a.device)
    # src[_semiring_helion.py:93]: for tile_p, tile_i, tile_k in hl.tile([n_p, n_i, n_k]):
    _BLOCK_SIZE_0_c1 = 4
    _BLOCK_SIZE_1_c1 = 8
    _BLOCK_SIZE_2_c1 = 32
    # src[_semiring_helion.py:93]: for tile_p, tile_i, tile_k in hl.tile([n_p, n_i, n_k]):
    # src[_semiring_helion.py:94]:     running_max = hl.full([tile_p, tile_i, tile_k], float("-inf"), dtype=a.dtype)
    # src[_semiring_helion.py:95]:     for tile_j in hl.tile(n_j):
    # src[_semiring_helion.py:93-100]: ...
    _launcher(_helion__max_bmm_kernel_c1, ((n_p + _BLOCK_SIZE_0_c1 - 1) // _BLOCK_SIZE_0_c1 * ((n_i + _BLOCK_SIZE_1_c1 - 1) // _BLOCK_SIZE_1_c1) * ((n_k + _BLOCK_SIZE_2_c1 - 1) // _BLOCK_SIZE_2_c1),), a, b, out, a.stride(0), a.stride(1), a.stride(2), b.stride(0), b.stride(1), b.stride(2), out.stride(0), out.stride(1), out.stride(2), n_p, n_i, n_k, n_j, num_warps=1, num_stages=1)
    # src[_semiring_helion.py:101]: return out
    return out

# =================================================================
# Config 2
# =================================================================

_BLOCK_SIZE_0_c2 = tl.constexpr(16)
_BLOCK_SIZE_2_c2 = tl.constexpr(4)
_BLOCK_SIZE_1_c2 = tl.constexpr(4)
_BLOCK_SIZE_3_c2 = tl.constexpr(16)

@triton.jit
def _helion__max_bmm_kernel_c2(a, b, out, a_stride_0, a_stride_1, a_stride_2, b_stride_0, b_stride_1, b_stride_2, out_stride_0, out_stride_1, out_stride_2, n_p, n_k, n_i, n_j):
    # src[_semiring_helion.py:93]: for tile_p, tile_i, tile_k in hl.tile([n_p, n_i, n_k]):
    num_blocks_0 = tl.cdiv(n_p, _BLOCK_SIZE_0_c2)
    num_blocks_1 = tl.cdiv(n_k, _BLOCK_SIZE_2_c2)
    pid_0 = tl.program_id(0) % num_blocks_0
    pid_1 = tl.program_id(0) // num_blocks_0 % num_blocks_1
    pid_2 = tl.program_id(0) // (num_blocks_0 * num_blocks_1)
    offset_0 = pid_0 * _BLOCK_SIZE_0_c2
    indices_0 = (offset_0 + tl.arange(0, _BLOCK_SIZE_0_c2)).to(tl.int32)
    mask_0 = indices_0 < n_p
    offset_2 = pid_1 * _BLOCK_SIZE_2_c2
    indices_2 = (offset_2 + tl.arange(0, _BLOCK_SIZE_2_c2)).to(tl.int32)
    mask_2 = indices_2 < n_k
    offset_1 = pid_2 * _BLOCK_SIZE_1_c2
    indices_1 = (offset_1 + tl.arange(0, _BLOCK_SIZE_1_c2)).to(tl.int32)
    mask_1 = indices_1 < n_i
    # src[_semiring_helion.py:94]: running_max = hl.full([tile_p, tile_i, tile_k], float("-inf"), dtype=a.dtype)
    running_max = tl.full([_BLOCK_SIZE_0_c2, _BLOCK_SIZE_1_c2, _BLOCK_SIZE_2_c2], float('-inf'), tl.float32)
    # src[_semiring_helion.py:95]: for tile_j in hl.tile(n_j):
    # src[_semiring_helion.py:96]:     terms = (
    # src[_semiring_helion.py:97]:         a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
    # src[_semiring_helion.py:95-99]: ...
    for offset_3 in tl.range(0, tl.cast(n_j, tl.int32), _BLOCK_SIZE_3_c2, num_stages=1, disallow_acc_multi_buffer=True, flatten=False):
        indices_3 = offset_3 + tl.arange(0, _BLOCK_SIZE_3_c2).to(tl.int32)
        mask_3 = indices_3 < n_j
        running_max_copy = running_max
        running_max_copy_0 = running_max_copy
        # src[_semiring_helion.py:97]: a[tile_p, tile_i, tile_j][:, :, :, None] + b[tile_p, tile_j, tile_k][:, None, :, :]
        load = tl.load(a + (indices_0[:, None, None] * a_stride_0 + indices_1[None, :, None] * a_stride_1 + indices_3[None, None, :] * a_stride_2), mask_0[:, None, None] & mask_1[None, :, None] & mask_3[None, None, :], other=0)
        subscript = load[:, :, :, None]
        load_1 = tl.load(b + (indices_0[:, None, None] * b_stride_0 + indices_3[None, :, None] * b_stride_1 + indices_2[None, None, :] * b_stride_2), mask_0[:, None, None] & mask_3[None, :, None] & mask_2[None, None, :], other=0)
        subscript_1 = load_1[:, None, :, :]
        v_0 = subscript + subscript_1
        # src[_semiring_helion.py:99]: running_max = torch.maximum(running_max, torch.amax(terms, dim=2))
        _mask_to = tl.where(mask_0[:, None, None, None] & mask_1[None, :, None, None] & mask_3[None, None, :, None] & mask_2[None, None, None, :], v_0, tl.full([], float('-inf'), tl.float32))
        amax = tl.cast(tl.max(_mask_to, 2), tl.float32)
        running_max = triton_helpers.maximum(running_max_copy_0, amax)
    # src[_semiring_helion.py:100]: out[tile_p, tile_i, tile_k] = running_max
    tl.store(out + (indices_0[:, None, None] * out_stride_0 + indices_1[None, :, None] * out_stride_1 + indices_2[None, None, :] * out_stride_2), running_max, mask_0[:, None, None] & mask_1[None, :, None] & mask_2[None, None, :])

def __max_bmm_kernel_c2(a: Tensor, b: Tensor, *, _launcher=_default_launcher):
    # src[_semiring_helion.py:90]: n_p, n_i, n_j = a.shape
    n_p, n_i, n_j = a.shape
    # src[_semiring_helion.py:91]: n_k = b.size(-1)
    n_k = b.size(-1)
    # src[_semiring_helion.py:92]: out = torch.empty([n_p, n_i, n_k], dtype=a.dtype, device=a.device)
    out = torch.empty([n_p, n_i, n_k], dtype=a.dtype, device=a.device)
    # src[_semiring_helion.py:93]: for tile_p, tile_i, tile_k in hl.tile([n_p, n_i, n_k]):
    _BLOCK_SIZE_0_c2 = 16
    _BLOCK_SIZE_2_c2 = 4
    _BLOCK_SIZE_1_c2 = 4
    # src[_semiring_helion.py:93]: for tile_p, tile_i, tile_k in hl.tile([n_p, n_i, n_k]):
    # src[_semiring_helion.py:94]:     running_max = hl.full([tile_p, tile_i, tile_k], float("-inf"), dtype=a.dtype)
    # src[_semiring_helion.py:95]:     for tile_j in hl.tile(n_j):
    # src[_semiring_helion.py:93-100]: ...
    _launcher(_helion__max_bmm_kernel_c2, ((n_p + _BLOCK_SIZE_0_c2 - 1) // _BLOCK_SIZE_0_c2 * ((n_k + _BLOCK_SIZE_2_c2 - 1) // _BLOCK_SIZE_2_c2) * ((n_i + _BLOCK_SIZE_1_c2 - 1) // _BLOCK_SIZE_1_c2),), a, b, out, a.stride(0), a.stride(1), a.stride(2), b.stride(0), b.stride(1), b.stride(2), out.stride(0), out.stride(1), out.stride(2), n_p, n_k, n_i, n_j, num_warps=1, num_stages=1)
    # src[_semiring_helion.py:101]: return out
    return out

# =================================================================
# Heuristic dispatch
# =================================================================

# === Kernel: _max_bmm_kernel ===


def key__max_bmm_kernel(*args) -> int:
    _arg0_dim1 = int(args[0].shape[1]) if len(args) > 0 and isinstance(args[0], torch.Tensor) and args[0].ndim > 1 else 0
    if _arg0_dim1 <= 8.0:
        return 0
    else:
        if _arg0_dim1 <= 32.0:
            return 2
        else:
            return 1


# === Kernel: _contract_over_i ===


# === Kernel: _contract_over_j ===


# === Kernel: _contract_over_k ===



def _max_bmm_kernel(*args, **kwargs):
    return [
        __max_bmm_kernel_c0,
        __max_bmm_kernel_c1,
        __max_bmm_kernel_c2,
    ][key__max_bmm_kernel(*args)](*args, **kwargs)
